import Image from "next/image";
import Link from "next/link";
import { TallyButton } from "@/components/LeadForms";
import { LawnRobotProductSelector } from "@/components/LawnRobotProductSelector";
import { getInsights } from "@/lib/content";
import type { ProductDirection, SourcingProduct } from "@/lib/sourcingProducts";

const fits = [
  ["CC-01", ["Conditional fit", "Strong fit", "Strong fit", "—", "Strong fit"]],
  ["CC-02", ["—", "Strong fit", "Strong fit", "—", "Strong fit"]],
  ["CC-03", ["—", "Strong fit", "Strong fit", "Conditional fit", "Strong fit"]],
  ["CC-04", ["—", "Strong fit", "Strong fit", "—", "Strong fit"]],
  ["CC-05", ["—", "Strong fit", "Strong fit", "—", "Strong fit"]],
  ["CC-06", ["—", "Strong fit", "Strong fit", "Conditional fit", "Strong fit"]]
] as const;

const faqs = [
  ["Which commercial cleaning robot direction is most credible for a new entrant?", "Begin with one facility type and one repeatable workflow. Retail, office and warehouse platforms have different cleaning systems, safety conditions and service requirements."],
  ["When does autonomy create real value rather than a demonstration effect?", "Autonomy creates value when routes, operating windows, staff handoff and exception handling reduce real labor or improve consistency across repeated shifts."],
  ["Should buyers choose a scrubber, sweeper or hybrid platform?", "The answer depends on debris, floor finish, traffic and cleaning frequency. A hybrid platform is not automatically better if added complexity lowers reliability or makes service harder."],
  ["Which facilities are most ready for commercial cleaning robots?", "Facilities with repeatable open-floor routes, measurable labor pressure, trained operators and local service support are usually more credible than highly variable sites."],
  ["Which technical claims create the greatest purchasing risk?", "Runtime, coverage, navigation and obstacle avoidance can look strong in controlled demos. Test them during real traffic, layout changes, interruptions and daily maintenance."],
  ["Where can Chinese suppliers still differentiate?", "Strong suppliers can combine hardware iteration with deployment tools, fleet software, parts systems and service preparation. Price alone does not create a scalable platform."],
  ["What separates a pilot from a scalable deployment?", "A scalable deployment has repeatable setup, trained operators, documented service, measurable outcomes and economics that survive downtime and support."],
  ["What should buyers verify before selecting a platform?", "Verify facility value, repeatable site performance, supplier control of critical systems and local service economics after deployment."],
  ["How should buyers compare suppliers without public factory lists?", "Compare deployment evidence, safety testing, system control, software capability, parts and service readiness against the target facility—not a generic ranking."]
] as const;

const channels = ["Direct project sales", "Specialist dealer", "Facility services", "Private label", "Equipment rental / leasing"];

function SuccessCard({ number, item, title, text }: { number: string; item?: ProductDirection; title: string; text: string }) {
  if (!item) return null;
  return <article><div className="sourcing-lawn-success-image"><Image src={item.image} alt={item.imageAlt} fill sizes="(max-width: 760px) 100vw, 33vw" /><span>{number}</span></div><h3>{title}</h3><p>{text}</p></article>;
}

export function CommercialCleaningLanding({ product }: { product: SourcingProduct }) {
  const directions = product.directions ?? [];
  const related = product.relatedArticleSlugs.flatMap((slug) => {
    const article = getInsights().find((item) => item.slug === slug);
    return article ? [article] : [];
  });
  const pageUrl = "https://worldcleanbiz.com/sourcing/commercial-cleaning";
  return <main className="sourcing-v3-page sourcing-lawn-page sourcing-commercial-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "Service", name: product.title, description: product.metaDescription, provider: { "@type": "Organization", name: "World Clean Biz", url: "https://worldcleanbiz.com" }, areaServed: "Worldwide", url: pageUrl }) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://worldcleanbiz.com" }, { "@type": "ListItem", position: 2, name: "Sourcing", item: "https://worldcleanbiz.com/sourcing" }, { "@type": "ListItem", position: 3, name: product.eyebrow, item: pageUrl }] }) }} />
    <section className="section-hero sourcing-product-hero sourcing-lawn-hero"><div className="sourcing-v3-container sourcing-product-hero-grid"><div><p className="sourcing-v3-kicker">Where Commercial Cleaning Automation Can Create Real Value</p><h1>Choose the Facility Opportunity Before You Choose the Robot</h1><p className="sourcing-product-intro">Commercial cleaning robots are separating into facility-specific platforms—from retail scrubbers and office robots to warehouse sweepers, healthcare systems and docked service fleets. The opportunity depends on workflow, deployment conditions and service economics.</p><div className="sourcing-lawn-hero-actions"><a className="sourcing-v3-button" href="#product-options">Explore the Product Opportunities</a><TallyButton className="sourcing-lawn-secondary-button" form="sourcing" conversionGroup="sourcing" ctaLocation="commercial_cleaning_hero_custom_brief" inquiryIntent="product_sourcing" productCategory={product.productCategory}>Test My Deployment Thesis</TallyButton></div><p className="sourcing-lawn-hero-fit">For equipment brands, dealers, facility service companies and project buyers deciding where commercial cleaning automation can scale.</p></div><img src={product.image} alt={product.imageAlt} /></div></section>
    <section className="section sourcing-lawn-audience-section"><div className="sourcing-v3-container"><p className="sourcing-v3-kicker">The Decisions Buyers Are Facing</p><h2>Built for Buyers Deciding Where to Deploy Commercial Cleaning Robots</h2><div className="sourcing-lawn-audience-grid"><article><span>Enter</span><h3>Choose a first facility use case with credible automation value</h3></article><article><span>Expand</span><h3>Add a platform for a new facility, service or operating model</h3></article><article><span>Differentiate</span><h3>Build a deployment and service advantage beyond hardware</h3></article><article><span>De-risk</span><h3>Replace a weak pilot or unsupported platform before scaling</h3></article></div></div></section>
    <LawnRobotProductSelector products={directions} productCategory={product.productCategory} ctaPrefix="commercial_cleaning" ariaLabel="Choose a commercial cleaning robot product direction" />
    <section className="section sourcing-lawn-landscape-section"><div className="sourcing-v3-container"><p className="sourcing-v3-kicker">Six-Platform Opportunity Landscape</p><div className="sourcing-lawn-visual-heading"><h2>Where the Six Commercial Platforms Compete</h2><p>Different platforms create value through different facility complexity, deployment depth and service requirements.</p></div><figure className="sourcing-lawn-landscape"><figcaption><span>World Clean Biz editorial assessment</span><small>Directional positioning, not measured market data. Final decisions require facility trials and supplier evidence.</small></figcaption><div className="sourcing-lawn-landscape-y"><span>Complex public and specialist facilities</span><span>Repeatable controlled environments</span></div><div className="sourcing-lawn-landscape-plot">{directions.map((item, index) => <div className={`sourcing-lawn-landscape-marker is-rm0${index + 1}`} key={item.id}><strong>{item.id}</strong><span>{item.name}</span></div>)}</div><div className="sourcing-lawn-landscape-x"><span>Machine-led sale</span><span>Deployment and service-led value</span></div></figure></div></section>
    <section className="section section-muted sourcing-lawn-channel-section"><div className="sourcing-v3-container"><p className="sourcing-v3-kicker">Platform × Route-to-Market Fit</p><div className="sourcing-lawn-visual-heading"><h2>Which Commercial Routes Fit Each Product Platform?</h2><p>Fit depends on deployment support, operator training, service coverage and the buyer's ability to manage a pilot.</p></div><div className="sourcing-lawn-assessment-legend"><strong>World Clean Biz editorial assessment</strong><span><i className="is-strong" />Strong fit</span><span><i className="is-conditional" />Conditional fit</span><span>— Not a natural primary route</span></div><div className="sourcing-lawn-table-wrap" tabIndex={0}><table className="sourcing-lawn-channel-matrix"><thead><tr><th>Product platform</th>{channels.map((channel) => <th key={channel}>{channel}</th>)}</tr></thead><tbody>{fits.map(([id, cells]) => <tr key={id}><th><strong>{id}</strong><span>{directions.find((item) => item.id === id)?.name}</span></th>{cells.map((cell, index) => <td className={cell === "Strong fit" ? "is-strong" : cell === "Conditional fit" ? "is-conditional" : ""} key={index}><span>{cell}</span></td>)}</tr>)}</tbody></table></div></div></section>
    <section className="section sourcing-lawn-success-section"><div className="sourcing-v3-container"><p className="sourcing-v3-kicker">Opportunity Conditions</p><h2>Three Conditions That Decide Whether a Deployment Can Scale</h2><div className="sourcing-lawn-success-grid"><SuccessCard number="01" item={directions[0]} title="A valuable facility workflow" text="The platform must solve a measurable labor, consistency, safety or coverage problem in the target site." /><SuccessCard number="02" item={directions[4]} title="Repeatable real-site performance" text="Navigation, cleaning and exception recovery must work during the traffic and layout changes the facility actually has." /><SuccessCard number="03" item={directions[5]} title="Service economics after deployment" text="Training, downtime, parts, remote support and local service cannot consume the value created by automation." /></div></div></section>
    <section className="section sourcing-lawn-trust-section"><div className="sourcing-v3-container sourcing-lawn-trust"><img src="/images/industry/about-denny-portrait-event.jpg" alt="Denny, founder of World Clean Biz, at a cleaning industry event" /><div><p className="sourcing-v3-kicker">Industry judgment behind the deployment decision</p><h2>A successful demonstration is not yet a scalable commercial program</h2><p>Denny reviews whether facility value, product evidence, supplier capability and the service model reinforce one another strongly enough to justify a pilot and the next deployment.</p><ul><li>Founder, World Clean Biz</li><li>Organizer, World Clean Expo</li><li>Inside the cleaning industry since 2006</li></ul></div></div></section>
    <section className="section section-muted sourcing-lawn-evidence-section"><div className="sourcing-v3-container"><p className="sourcing-v3-kicker">Commercial Go / No-Go</p><div className="sourcing-lawn-visual-heading"><h2>Four Decisions Before You Back a Commercial Platform</h2><p>Move forward only when facility value, performance evidence, supplier capability and service economics reinforce one another.</p></div><ol className="sourcing-lawn-evidence-flow">{[["Opportunity", "Is the facility problem valuable?", ["Labor or consistency value", "Repeatable site type", "Buyer ownership"]], ["Platform", "Does the real-site pilot prove it?", ["Navigation and safety", "Cleaning result", "Exception recovery"]], ["Supplier", "Can capability survive deployment?", ["System control", "Deployment tools", "Parts and training"]], ["Economics", "Does value survive after launch?", ["Utilization and uptime", "Support cost", "Service margin"]]].map(([label, question, proof], index) => <li key={label as string}><span>0{index + 1}</span><strong>{label as string}</strong><h3>{question as string}</h3><ul>{(proof as string[]).map((item) => <li key={item}>{item}</li>)}</ul></li>)}</ol></div></section>
    <section className="section section-muted sourcing-lawn-faq-section"><div className="sourcing-v3-container sourcing-lawn-faq"><div><p className="sourcing-v3-kicker">Industry Opportunity Questions</p><h2>The Deployment Decisions Buyers Are Debating Now</h2><p>These commercial, technical and operational choices shape where commercial cleaning automation can scale.</p><img className="sourcing-lawn-faq-visual" src={directions[3]?.image || product.image} alt={directions[3]?.imageAlt || product.imageAlt} /></div><div>{faqs.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></div></section>
    <section className="section sourcing-lawn-final-section"><div className="sourcing-v3-container sourcing-lawn-final-cta"><div><p className="sourcing-v3-kicker">Make the Opportunity Specific</p><h2>Turn a Facility Opportunity Into a Deployment Brief</h2><p>Define the target facility, cleaning workflow, operating window, route to market, service model and evidence that must be proven.</p></div><div className="sourcing-lawn-final-actions"><TallyButton className="sourcing-v3-button" form="sourcing" conversionGroup="sourcing" ctaLocation="commercial_cleaning_final_custom_brief" inquiryIntent="product_sourcing" productCategory={product.productCategory}>Evaluate My Deployment Opportunity</TallyButton><a href="#product-options">Discuss a Selected Platform</a></div></div></section>
    <section className="section"><div className="sourcing-v3-container"><p className="sourcing-v3-kicker">Related Intelligence</p><h2>Research the category before choosing a supplier</h2><div className="sourcing-product-grid">{related.map((article) => <article className="sourcing-pool-related-card" key={article.slug}>{article.coverImage ? <img src={article.coverImage} alt={article.coverAlt || article.title} /> : null}<h3>{article.title}</h3><p>{article.excerpt}</p><Link href={`/blog/${article.slug}`}>Read the analysis</Link></article>)}</div></div></section>
  </main>;
}
