import Image from "next/image";
import Link from "next/link";
import { TallyButton } from "@/components/LeadForms";
import { LawnRobotProductSelector } from "@/components/LawnRobotProductSelector";
import { getInsights } from "@/lib/content";
import type { SourcingProduct } from "@/lib/sourcingProducts";

const channelFits = [
  ["FW-01", "Retail Wet-Clean Starter", ["Strong fit", "Strong fit", "Conditional fit", "Conditional fit", "—"]],
  ["FW-02", "Cordless Premium Platform", ["Conditional fit", "Strong fit", "Strong fit", "Conditional fit", "—"]],
  ["FW-03", "Deep-Clean Design Platform", ["Conditional fit", "Conditional fit", "Strong fit", "—", "—"]],
  ["FW-04", "Ecommerce Value Platform", ["Conditional fit", "Strong fit", "Conditional fit", "Strong fit", "—"]],
  ["FW-05", "Light-Commercial Service Platform", ["—", "—", "Strong fit", "—", "Strong fit"]],
  ["FW-06", "Self-Cleaning Convenience Platform", ["Strong fit", "Strong fit", "Conditional fit", "Conditional fit", "—"]]
] as const;

const faqs = [
  ["Which hard floor washer direction is most credible for a new entrant?", "The strongest opening is usually a focused customer problem rather than a full-category claim. Retail starters, ecommerce value platforms and maintenance-led premium products each need a clear reason to exist in a specific channel."],
  ["Is the category moving toward premium convenience or value products?", "Both routes can work. Premium depends on reliable cleaning, docking and maintenance; value depends on avoiding returns and service costs that erase the price advantage."],
  ["Which features create customer value rather than marketing noise?", "Visible pickup, edge cleaning, manageable tanks, a clean roller and low-friction maintenance are meaningful. A long mode list is not a substitute for repeatable cleaning and ownership."],
  ["Which platforms fit ecommerce and mass retail?", "The product needs a simple use case, resilient packaging, consumer-led setup and support demand that does not consume channel margin. These are commercial conditions, not only product features."],
  ["Where can Chinese suppliers still differentiate?", "The opportunity is in turning fast iteration into stable water systems, battery performance, material quality, consumables and service readiness. Cost alone is not durable differentiation."],
  ["Which technical claims create the greatest sourcing risk?", "Runtime, edge performance, self-cleaning, drying and odour control can look stronger in a demonstration than in daily ownership. Convert claims into repeatable target-market tests before using them in sales material."],
  ["What separates a scalable platform from a one-season product?", "A scalable platform combines controlled quality, serviceable components, reliable consumables and an after-sales plan that survives returns, warranty and product updates."],
  ["What should buyers verify before selecting a platform?", "Verify that the customer problem is valuable, cleaning performance is repeatable, the supplier controls critical systems, and margin survives after consumables, returns and service."],
  ["How should buyers compare suppliers without public factory lists?", "Compare product evidence, test depth, water-system control, component choices and after-sales preparation against your own market and channel requirements—not a generic supplier ranking."]
] as const;

export function FloorWasherLanding({ product }: { product: SourcingProduct }) {
  const directions = product.directions ?? [];
  const related = product.relatedArticleSlugs.flatMap((slug) => { const article = getInsights().find((item) => item.slug === slug); return article ? [article] : []; });
  return <main className="sourcing-v3-page sourcing-lawn-page sourcing-floor-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "Service", name: product.title, description: product.metaDescription, provider: { "@type": "Organization", name: "World Clean Biz", url: "https://worldcleanbiz.com" }, areaServed: "Worldwide", url: "https://worldcleanbiz.com/sourcing/floor-washers" }) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://worldcleanbiz.com" }, { "@type": "ListItem", position: 2, name: "Sourcing", item: "https://worldcleanbiz.com/sourcing" }, { "@type": "ListItem", position: 3, name: product.eyebrow, item: "https://worldcleanbiz.com/sourcing/floor-washers" }] }) }} />
    <section className="section-hero sourcing-product-hero sourcing-lawn-hero"><div className="sourcing-v3-container sourcing-product-hero-grid"><div><p className="sourcing-v3-kicker">Where the Next Hard Floor Washer Opportunities Are Forming</p><h1>Choose the Market Opportunity Before You Choose the Factory</h1><p className="sourcing-product-intro">Hard floor washers are separating into distinct platforms—from accessible wet-clean starters to cordless premium machines, ecommerce value offers and service-led commercial systems. The opportunity depends on the cleaning problem, customer and channel the platform is built to serve.</p><div className="sourcing-lawn-hero-actions"><a className="sourcing-v3-button" href="#product-options">Explore the Product Opportunities</a><TallyButton className="sourcing-lawn-secondary-button" form="sourcing" conversionGroup="sourcing" ctaLocation="floor_washer_hero_custom_brief" inquiryIntent="product_sourcing" productCategory={product.productCategory}>Test My Product Thesis</TallyButton></div><p className="sourcing-lawn-hero-fit">For brands, importers, distributors and retailers deciding where to compete in hard floor care—and which product platform can support that position.</p></div><img src={product.image} alt={product.imageAlt} /></div></section>
    <section className="section sourcing-lawn-audience-section"><div className="sourcing-v3-container"><p className="sourcing-v3-kicker">The Decisions Buyers Are Facing</p><h2>Built for Buyers Deciding Where to Play in Hard Floor Care</h2><div className="sourcing-lawn-audience-grid"><article><span>Enter</span><h3>Choose a credible first platform for entering wet floor care</h3></article><article><span>Expand</span><h3>Add a product that opens a new user, price or channel position</h3></article><article><span>Differentiate</span><h3>Find a visible reason to win beyond a longer feature list</h3></article><article><span>De-risk</span><h3>Replace a weak supplier or short-lived product before scaling</h3></article></div></div></section>
    <LawnRobotProductSelector products={directions} productCategory={product.productCategory} ctaPrefix="floor_washer" ariaLabel="Choose a hard floor washer product direction" />
    <section className="section sourcing-lawn-landscape-section"><div className="sourcing-v3-container"><p className="sourcing-v3-kicker">Six-Platform Opportunity Landscape</p><div className="sourcing-lawn-visual-heading"><h2>Where the Six Product Platforms Compete</h2><p>Different floor washer platforms create value through different cleaning moments, ownership models and channels.</p></div><figure className="sourcing-lawn-landscape"><figcaption><span>World Clean Biz editorial assessment</span><small>Directional positioning, not measured market data. Final decisions require target-market and supplier evidence.</small></figcaption><div className="sourcing-lawn-landscape-y"><span>Specialist and professional use</span><span>Broad residential adoption</span></div><div className="sourcing-lawn-landscape-plot">{directions.map((item, index) => <div className={`sourcing-lawn-landscape-marker is-rm0${index + 1}`} key={item.id}><strong>{item.id}</strong><span>{item.name}</span></div>)}</div><div className="sourcing-lawn-landscape-x"><span>Accessible entry</span><span>Premium product and service value</span></div></figure></div></section>
    <section className="section section-muted sourcing-lawn-channel-section"><div className="sourcing-v3-container"><p className="sourcing-v3-kicker">Platform × Channel Fit</p><div className="sourcing-lawn-visual-heading"><h2>Which Channels Fit Each Product Platform?</h2><p>Fit depends on the cleaning story, customer education, service capability and ownership friction after the sale.</p></div><div className="sourcing-lawn-assessment-legend"><strong>World Clean Biz editorial assessment</strong><span><i className="is-strong" />Strong fit</span><span><i className="is-conditional" />Conditional fit</span><span>— Not a natural primary route</span></div><div className="sourcing-lawn-table-wrap" tabIndex={0}><table className="sourcing-lawn-channel-matrix"><thead><tr><th>Product platform</th>{["Retail", "Ecommerce", "Specialist dealer", "Private label", "Professional / project sales"].map((x) => <th key={x}>{x}</th>)}</tr></thead><tbody>{channelFits.map(([id, name, cells]) => <tr key={id}><th><strong>{id}</strong><span>{name}</span></th>{cells.map((cell, i) => <td className={cell === "Strong fit" ? "is-strong" : cell === "Conditional fit" ? "is-conditional" : ""} key={i}><span>{cell}</span></td>)}</tr>)}</tbody></table></div></div></section>
    <section className="section sourcing-lawn-success-section"><div className="sourcing-v3-container"><p className="sourcing-v3-kicker">Opportunity Conditions</p><h2>Three Conditions That Decide Whether the Opportunity Can Scale</h2><div className="sourcing-lawn-success-grid">{[["01", directions[0], "A clear cleaning problem", "The platform must solve a visible issue in everyday mess, floor type, maintenance or cleaning time."], ["02", directions[2], "Repeatable real-floor performance", "Pickup, edge coverage, water control and hygiene must work across the conditions the customer actually has."], ["03", directions[4], "Channel economics after the sale", "Returns, consumables, warranty, replacement parts and service cannot consume the margin that made the quotation attractive."]].map(([number, item, title, text]) => <article key={number as string}><div className="sourcing-lawn-success-image"><Image src={(item as typeof directions[number extends "01" ? 0 : never])?.image || product.image} alt={(item as typeof directions[number extends "01" ? 0 : never])?.imageAlt || product.imageAlt} fill sizes="(max-width: 760px) 118px, 33vw" /><span>{number as string}</span></div><h3>{title as string}</h3><p>{text as string}</p></article>)}</div></div></section>
    <section className="section sourcing-lawn-trust-section"><div className="sourcing-v3-container sourcing-lawn-trust"><img src="/images/industry/about-denny-portrait-event.jpg" alt="Denny, founder of World Clean Biz, at a cleaning industry event" /><div><p className="sourcing-v3-kicker">Industry judgment behind the product decision</p><h2>A platform can look convincing long before it becomes a viable business</h2><p>Denny reviews whether opportunity, product evidence, supplier capability and execution model reinforce one another strongly enough to justify the next investment—not whether the quotation looks attractive.</p><ul><li>Founder, World Clean Biz</li><li>Organizer, World Clean Expo</li><li>Inside the cleaning industry since 2006</li></ul></div></div></section>
    <section className="section section-muted sourcing-lawn-evidence-section"><div className="sourcing-v3-container"><p className="sourcing-v3-kicker">Commercial Go / No-Go</p><div className="sourcing-lawn-visual-heading"><h2>Four Decisions Before You Back a Platform</h2><p>Move forward only when the opportunity, product evidence, supplier capability and after-sale economics reinforce one another.</p></div><ol className="sourcing-lawn-evidence-flow">{[["Opportunity", "Is the customer problem valuable?", ["Reason to switch", "Addressable floor use", "Channel relevance"]], ["Platform", "Does real-floor performance prove it?", ["Pickup and edge cleaning", "Water and hygiene control", "Ownership experience"]], ["Supplier", "Can capability survive scale?", ["Critical-system control", "Test depth", "Parts and service"]], ["Economics", "Does margin survive after the sale?", ["Price and margin", "Returns and warranty", "Quality and compliance"]]].map(([label, question, evidence], index) => <li key={label as string}><span>0{index + 1}</span><strong>{label as string}</strong><h3>{question as string}</h3><ul>{(evidence as string[]).map((item) => <li key={item}>{item}</li>)}</ul></li>)}</ol></div></section>
    <section className="section section-muted sourcing-lawn-faq-section"><div className="sourcing-v3-container sourcing-lawn-faq"><div><p className="sourcing-v3-kicker">Industry Opportunity Questions</p><h2>The Product Decisions Buyers Are Debating Now</h2><p>These are commercial and technical choices that shape where hard floor washer growth can come from next.</p><img className="sourcing-lawn-faq-visual" src="/images/sourcing/floor-washers/fw-04-ecommerce-spill-concept.png" alt="Illustrative hard floor washer under product assessment" /></div><div>{faqs.map(([q, a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
    <section className="section sourcing-lawn-final-section"><div className="sourcing-v3-container sourcing-lawn-final-cta"><div><p className="sourcing-v3-kicker">Make the Opportunity Specific</p><h2>Turn a Market Opportunity Into a Product Brief</h2><p>Define the target customer, use environment, channel, price position and reason the product should win. That is the starting point for identifying the platform, supplier capability and evidence worth pursuing.</p></div><div className="sourcing-lawn-final-actions"><TallyButton className="sourcing-v3-button" form="sourcing" conversionGroup="sourcing" ctaLocation="floor_washer_final_custom_brief" inquiryIntent="product_sourcing" productCategory={product.productCategory}>Evaluate My Product Opportunity</TallyButton><a href="#product-options">Discuss a Selected Product</a></div></div></section>
    <section className="section"><div className="sourcing-v3-container"><p className="sourcing-v3-kicker">Related Intelligence</p><h2>Research the category before choosing a supplier</h2><div className="sourcing-product-grid">{related.map((article) => <article className="sourcing-pool-related-card" key={article.slug}>{article.coverImage ? <img src={article.coverImage} alt={article.coverAlt || article.title} /> : null}<h3>{article.title}</h3><p>{article.excerpt}</p><Link href={`/blog/${article.slug}`}>Read the analysis</Link></article>)}</div></div></section>
  </main>;
}
