import Image from "next/image";
import Link from "next/link";
import { TallyButton } from "@/components/LeadForms";
import { LawnRobotProductSelector } from "@/components/LawnRobotProductSelector";
import { getInsights } from "@/lib/content";
import type { SourcingProduct } from "@/lib/sourcingProducts";

const fits = [
  ["RM-01", "Cordless Retail Starter", ["Strong fit", "Strong fit", "Conditional fit", "Conditional fit", "—"]],
  ["RM-02", "Wall-Climbing Step-Up", ["Conditional fit", "Strong fit", "Strong fit", "Conditional fit", "—"]],
  ["RM-03", "Cordless Premium Platform", ["—", "Conditional fit", "Strong fit", "Conditional fit", "—"]],
  ["RM-04", "Proven Corded Value", ["Strong fit", "Conditional fit", "Conditional fit", "Strong fit", "—"]],
  ["RM-05", "Large-Pool Service Platform", ["—", "—", "Strong fit", "—", "Strong fit"]],
  ["RM-06", "Ecommerce Value Platform", ["Conditional fit", "Strong fit", "Conditional fit", "Strong fit", "—"]]
] as const;
const faqs = [
  ["Which pool robot direction is most credible for a new entrant?", "Start with a narrow pool type, customer and channel problem. A cordless retail starter or proven value platform can be more credible than trying to match every premium feature at once."],
  ["Is the market moving toward premium cordless products or value platforms?", "Both routes can work. Cordless convenience supports premium pricing only when reliability and ownership experience are proven; value works only if returns and service do not erase the saving."],
  ["Can cordless robots replace corded products in every pool?", "No. Cordless removes a visible ownership friction, but usable runtime, retrieval and charging must suit the target pool. Mature corded platforms remain relevant where predictable performance and repairability matter most."],
  ["Which features are customer value rather than marketing features?", "Coverage that matches the pool, filtration that handles expected debris, reliable wall performance and low-friction ownership are meaningful. More modes alone are not a reason to buy."],
  ["Which platforms fit ecommerce and mass retail?", "A clear use case, resilient packaging, consumer-led setup and controlled support demand matter more than an impressive feature list. These are channel economics questions, not just product questions."],
  ["Where can Chinese suppliers still differentiate?", "The opportunity is in turning iteration speed into stable waterproofing, testing, software, parts support and a position that the target channel can explain. Cost by itself is not durable differentiation."],
  ["Which technical claims create the greatest purchasing risk?", "Cleaning area, wall climbing, battery runtime and navigation can look stronger in specifications than in ordinary pools. Convert claims into repeatable target-market test scenarios before they reach packaging."],
  ["What separates a scalable platform from a one-season product?", "A scalable platform has controlled quality, serviceable components, a durable parts plan and supplier capability that survives warranty and model updates—not merely a compelling sample."],
  ["What should buyers verify before selecting a platform?", "Verify the customer problem, repeatable pool performance, supplier control of critical systems and channel economics after returns, warranty and service."],
  ["How should buyers compare suppliers without public factory lists?", "Compare product evidence, testing depth, component control, service preparation and execution capability against your own target market and channel—not a generic supplier ranking."]
] as const;

export function PoolRobotLanding({ product }: { product: SourcingProduct }) {
  const related = product.relatedArticleSlugs.flatMap((slug) => { const article = getInsights().find((item) => item.slug === slug); return article ? [article] : []; });
  const directions = product.directions ?? [];
  return <main className="sourcing-v3-page sourcing-lawn-page sourcing-pool-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "Service", name: product.title, description: product.metaDescription, provider: { "@type": "Organization", name: "World Clean Biz", url: "https://worldcleanbiz.com" }, areaServed: "Worldwide", url: "https://worldcleanbiz.com/sourcing/pool-robots" }) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://worldcleanbiz.com" }, { "@type": "ListItem", position: 2, name: "Sourcing", item: "https://worldcleanbiz.com/sourcing" }, { "@type": "ListItem", position: 3, name: product.eyebrow, item: "https://worldcleanbiz.com/sourcing/pool-robots" }] }) }} />
    <section className="section-hero sourcing-product-hero sourcing-lawn-hero"><div className="sourcing-v3-container sourcing-product-hero-grid"><div><p className="sourcing-v3-kicker">Where the Next Pool Robotics Opportunities Are Forming</p><h1>Choose the Market Opportunity Before You Choose the Factory</h1><p className="sourcing-product-intro">Pool robotics is separating into distinct platforms—from cordless retail starters to wall-climbing premium models, proven value products and service-led large-pool machines. The opportunity depends on the pool owner, channel and ownership problem the product solves.</p><div className="sourcing-lawn-hero-actions"><a className="sourcing-v3-button" href="#product-options">Explore the Product Opportunities</a><TallyButton className="sourcing-lawn-secondary-button" form="sourcing" conversionGroup="sourcing" ctaLocation="pool_robot_hero_custom_brief" inquiryIntent="product_sourcing" productCategory={product.productCategory}>Test My Product Thesis</TallyButton></div><p className="sourcing-lawn-hero-fit">For brands, importers, distributors and retailers deciding where to compete in pool robotics—and which product platform can support that position.</p></div><img src={product.image} alt={product.imageAlt} /></div></section>
    <section className="section sourcing-lawn-audience-section"><div className="sourcing-v3-container"><p className="sourcing-v3-kicker">The Decisions Buyers Are Facing</p><h2>Built for Buyers Deciding Where to Play in Pool Robotics</h2><div className="sourcing-lawn-audience-grid"><article><span>Enter</span><h3>Choose a credible first platform for entering pool robotics</h3></article><article><span>Expand</span><h3>Add a product that opens a new pool owner or price position</h3></article><article><span>Differentiate</span><h3>Find a visible reason to win beyond a longer specification sheet</h3></article><article><span>De-risk</span><h3>Replace a weak supplier or short-lived product before scaling</h3></article></div></div></section>
    <LawnRobotProductSelector products={directions} productCategory={product.productCategory} ctaPrefix="pool_robot" ariaLabel="Choose a pool robot product direction" />
    <section className="section sourcing-lawn-landscape-section"><div className="sourcing-v3-container"><p className="sourcing-v3-kicker">Six-Platform Opportunity Landscape</p><div className="sourcing-lawn-visual-heading"><h2>Where the Six Product Platforms Compete</h2><p>Different pool robot platforms create value through different pool types, channels and ownership models.</p></div><figure className="sourcing-lawn-landscape"><figcaption><span>World Clean Biz editorial assessment</span><small>Directional positioning, not measured market data. Final decisions require target-market and supplier evidence.</small></figcaption><div className="sourcing-lawn-landscape-y"><span>Specialist and professional use</span><span>Broad residential adoption</span></div><div className="sourcing-lawn-landscape-plot">{directions.map((item, index) => <div className={`sourcing-lawn-landscape-marker is-rm0${index + 1}`} key={item.id}><strong>{item.id}</strong><span>{item.name}</span></div>)}</div><div className="sourcing-lawn-landscape-x"><span>Accessible entry</span><span>Premium product and service value</span></div></figure></div></section>
    <section className="section section-muted sourcing-lawn-channel-section"><div className="sourcing-v3-container"><p className="sourcing-v3-kicker">Platform × Channel Fit</p><div className="sourcing-lawn-visual-heading"><h2>Which Channels Fit Each Product Platform?</h2><p>Fit depends on customer education, ownership friction, service capability and the clarity of the product's reason to buy.</p></div><div className="sourcing-lawn-assessment-legend"><strong>World Clean Biz editorial assessment</strong><span><i className="is-strong" />Strong fit</span><span><i className="is-conditional" />Conditional fit</span><span>— Not a natural primary route</span></div><div className="sourcing-lawn-table-wrap" tabIndex={0}><table className="sourcing-lawn-channel-matrix"><thead><tr><th>Product platform</th>{["Retail", "Ecommerce", "Specialist dealer", "Private label", "Professional / project sales"].map((x) => <th key={x}>{x}</th>)}</tr></thead><tbody>{fits.map(([id, name, cells]) => <tr key={id}><th><strong>{id}</strong><span>{name}</span></th>{cells.map((cell, i) => <td className={cell === "Strong fit" ? "is-strong" : cell === "Conditional fit" ? "is-conditional" : ""} key={i}><span>{cell}</span></td>)}</tr>)}</tbody></table></div></div></section>
    <section className="section sourcing-lawn-success-section"><div className="sourcing-v3-container"><p className="sourcing-v3-kicker">Opportunity Conditions</p><h2>Three Conditions That Decide Whether the Opportunity Can Scale</h2><div className="sourcing-lawn-success-grid">{[["01", directions[0], "A clear pool-owner problem", "The platform must solve a visible problem in pool size, debris, access or ownership friction."], ["02", directions[1], "Repeatable real-pool performance", "Coverage, filtration, waterproofing and recovery must work in the conditions the customer actually has."], ["03", directions[4], "Channel economics after the sale", "Returns, warranty, replacement parts and service cannot consume the margin that made the quotation attractive."]].map(([number, item, title, text]) => <article key={number as string}><div className="sourcing-lawn-success-image"><Image src={(item as typeof directions[number extends "01" ? 0 : never])?.image || product.image} alt={(item as typeof directions[number extends "01" ? 0 : never])?.imageAlt || product.imageAlt} fill sizes="(max-width: 760px) 118px, 33vw" /><span>{number as string}</span></div><h3>{title as string}</h3><p>{text as string}</p></article>)}</div></div></section>
    <section className="section sourcing-lawn-trust-section"><div className="sourcing-v3-container sourcing-lawn-trust"><img src="/images/industry/about-denny-portrait-event.jpg" alt="Denny, founder of World Clean Biz, at a cleaning industry event" /><div><p className="sourcing-v3-kicker">Industry judgment behind the product decision</p><h2>A platform can look convincing long before it becomes a viable business</h2><p>Denny reviews whether opportunity, product evidence, supplier capability and execution model reinforce one another strongly enough to justify the next investment—not whether the quotation looks attractive.</p><ul><li>Founder, World Clean Biz</li><li>Organizer, World Clean Expo</li><li>Inside the cleaning industry since 2006</li></ul></div></div></section>
    <section className="section section-muted sourcing-lawn-evidence-section"><div className="sourcing-v3-container"><p className="sourcing-v3-kicker">Commercial Go / No-Go</p><div className="sourcing-lawn-visual-heading"><h2>Four Decisions Before You Back a Platform</h2><p>Move forward only when the opportunity, product evidence, supplier capability and after-sale economics reinforce one another.</p></div><ol className="sourcing-lawn-evidence-flow">{[["Opportunity", "Is the customer problem valuable?", ["Reason to switch", "Addressable pool use", "Channel relevance"]], ["Platform", "Does real-pool performance prove it?", ["Coverage and filtration", "Waterproof reliability", "Ownership experience"]], ["Supplier", "Can capability survive scale?", ["Critical-system control", "Test depth", "Parts and service"]], ["Economics", "Does margin survive after the sale?", ["Price and margin", "Returns and warranty", "Quality and compliance"]]].map(([label, question, evidence], index) => <li key={label as string}><span>0{index + 1}</span><strong>{label as string}</strong><h3>{question as string}</h3><ul>{(evidence as string[]).map((item) => <li key={item}>{item}</li>)}</ul></li>)}</ol></div></section>
    <section className="section section-muted sourcing-lawn-faq-section"><div className="sourcing-v3-container sourcing-lawn-faq"><div><p className="sourcing-v3-kicker">Industry Opportunity Questions</p><h2>The Product Decisions Buyers Are Debating Now</h2><p>These are commercial and technical choices that shape where pool robotics growth can come from next.</p><img className="sourcing-lawn-faq-visual" src="/images/sourcing/pool-robots/rm-02-wall-climbing-concept.png" alt="Illustrative wall-climbing robotic pool cleaner under product assessment" /></div><div>{faqs.map(([q, a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
    <section className="section sourcing-lawn-final-section"><div className="sourcing-v3-container sourcing-lawn-final-cta"><div><p className="sourcing-v3-kicker">Make the Opportunity Specific</p><h2>Turn a Market Opportunity Into a Product Brief</h2><p>Define the target pool owner, use environment, channel, price position and reason the product should win. That is the starting point for identifying the platform, supplier capability and evidence worth pursuing.</p></div><div className="sourcing-lawn-final-actions"><TallyButton className="sourcing-v3-button" form="sourcing" conversionGroup="sourcing" ctaLocation="pool_robot_final_custom_brief" inquiryIntent="product_sourcing" productCategory={product.productCategory}>Evaluate My Product Opportunity</TallyButton><a href="#product-options">Discuss a Selected Product</a></div></div></section>
    <section className="section"><div className="sourcing-v3-container"><p className="sourcing-v3-kicker">Related Intelligence</p><h2>Research the category before choosing a supplier</h2><div className="sourcing-product-grid">{related.map((article) => <article className="sourcing-pool-related-card" key={article.slug}>{article.coverImage ? <img src={article.coverImage} alt={article.coverAlt || article.title} /> : null}<h3>{article.title}</h3><p>{article.excerpt}</p><Link href={`/blog/${article.slug}`}>Read the analysis</Link></article>)}</div></div></section>
  </main>;
}
