/** Explicit, reviewed media relationships. Brand backgrounds are never presented as event photos.
 * Product records retain their exact model; company/coverage images carry visible context labels.
 * Only append entries with a checked source and an existing explicit news/brand relationship.
 */
export type NewsVisual = {
  src: string;
  alt: string;
  kind: "product" | "company" | "coverage" | "event" | "context";
  label: string;
  caption: string;
  width?: number;
  height?: number;
  prepared?: boolean;
  fit?: "contain" | "cover";
  position?: string;
  sourceUrl?: string;
  sourceLabel?: string;
  relatedArticleSlug?: string;
  license?: { label: string; url: string };
};

export const newsStoryVisuals: Record<string, NewsVisual> = {
  "matic-fcc-conditional-approval-october-2026": {
    "src": "https://maticrobots.com/_next/static/media/buy-robot.4cd62895.webp",
    "alt": "Matic robot — official product reference image",
    "width": 808,
    "height": 1284,
    "kind": "product",
    "fit": "contain",
    "label": "Official product image",
    "caption": "Matic robot. Official product reference image; not a photograph of the FCC decision.",
    "sourceUrl": "https://maticrobots.com/",
    "sourceLabel": "Matic"
  },
  "midea-electrolux-north-america-jvs-operational-october-2026": {
    "src": "https://mmx.prnewswire.com/media/MS2001111/20261001142300EDT_image_1.jpg?id=OA2983544&p=original",
    "alt": "Midea and Electrolux cooperation signing photograph from the official announcement",
    "width": 2699,
    "height": 1799,
    "kind": "event",
    "fit": "cover",
    "position": "center 68%",
    "label": "Announcement image",
    "caption": "Midea and Electrolux cooperation photograph supplied with Midea’s announcement.",
    "sourceUrl": "https://www.prnewswire.com/news-releases/midea-and-electrolux-group-officially-begin-new-chapter-in-north-america-as-all-three-joint-ventures-go-live-302896703.html",
    "sourceLabel": "Midea / PR Newswire"
  },
  "roborock-s10-maxv-ultra-steam-korea-october-2026": {
    "src": "https://cdn.shopify.com/s/files/1/0332/8016/3885/files/VDSH_White_ID.png?v=1790751934",
    "alt": "Roborock S10 MaxV Ultra Steam, official Korean product image",
    "width": 1000,
    "height": 1000,
    "kind": "product",
    "fit": "contain",
    "label": "Official product image",
    "caption": "Roborock S10 MaxV Ultra Steam. Official product reference from the Korean product page.",
    "sourceUrl": "https://kr.roborock.com/pages/roborock-s10-maxv-ultra-steam",
    "sourceLabel": "Roborock South Korea"
  },
  "lionsbot-wisag-r5-development-interclean-2026": {
    "src": "https://mma.prnewswire.com/media/2951937/2026_03_30_LionsbotxWISAG_r5_v03__1.mp4?p=thumbnail",
    "width": 512,
    "height": 288,
    "sourceUrl": "https://www.prnewswire.com/news-releases/lionsbot-and-wisag-demonstrate-practitioner-driven-robotics-innovation-with-r5-ahead-of-interclean-2026-302736952.html",
    "kind": "product",
    "label": "Official product image",
    "alt": "LionsBot R5 Scrub in the WISAG collaboration video",
    "caption": "LionsBot R5 Scrub. Thumbnail from the official LionsBot / WISAG collaboration video.",
    "sourceLabel": "LionsBot / PR Newswire",
    "fit": "contain"
  },
  "ego-aura-r2-march-availability-february-2026": {
    "src": "https://cdn.mos.cms.futurecdn.net/TebzTqPGu9tHg3DjXteRMg-2560-80.jpg",
    "width": 2560,
    "height": 1440,
    "sourceUrl": "https://www.t3.com/home-living/garden/ego-launches-new-robot-lawn-mower-lineup-for-complex-gardens-and-theyre-completely-wire-free",
    "kind": "product",
    "label": "Product reference",
    "alt": "EGO AURA-R2 mower lineup",
    "caption": "EGO AURA-R2 lineup pictured in the original report. Product reference image, not a photograph of a particular customer installation.",
    "sourceLabel": "T3 / EGO",
    "fit": "contain"
  },
  "huibo-solar-cleaning-robot-tender-december-2025": {
    "src": "https://q7.itc.cn/images01/20251224/b7523d67e5184f08ac37615ae71adfe2.png",
    "width": 1080,
    "height": 719,
    "sourceUrl": "https://www.huiborobot.com/company/1027.html",
    "kind": "event",
    "label": "Announcement image",
    "alt": "Huibo solar-cleaning equipment pictured in its procurement announcement",
    "caption": "Solar-cleaning equipment pictured in Huibo’s December 2025 procurement announcement.",
    "sourceLabel": "Huibo",
    "fit": "contain"
  },
  "avc-january-october-robot-vacuum-sales-november-2025": {
    "src": "https://img08.mysteelcdn.com/wz/uploaded/steel/2025/11/18/8f3ce7ec352c482082f4e75a1d1fee3a.png",
    "width": 831,
    "height": 442,
    "sourceUrl": "https://news.mysteel.com/a/25111815/0576CD3A0029DEDD.html",
    "kind": "event",
    "label": "Source chart",
    "alt": "AVC China robot vacuum retail sales chart for January to October 2025",
    "caption": "AVC chart reproduced with the original market report, January–October 2025.",
    "sourceLabel": "AVC / Mysteel",
    "fit": "contain"
  },
  "dji-romo-european-rollout-october-2025": {
    "src": "https://mma.prnewswire.com/media/2804693/image.jpg?p=facebook",
    "width": 600,
    "height": 315,
    "sourceUrl": "https://www.prnewswire.com/news-releases/djis-first-all-in-one-robot-vacuum-romo-flagship-technology-flies-into-the-home-302595376.html",
    "kind": "product",
    "label": "Official product image",
    "alt": "DJI ROMO robot vacuum lineup in its European launch announcement",
    "caption": "DJI ROMO lineup from the official European launch announcement.",
    "sourceLabel": "DJI / PR Newswire",
    "fit": "contain"
  },
  "gausium-scrubber-75-chongqing-east-station-october-2025": {
    "src": "https://gausium.com/wp-content/uploads/2025/10/DSC04524-scaled.jpg",
    "width": 2560,
    "height": 2223,
    "sourceUrl": "https://gausium.com/case/chongqing-east-railway-station/",
    "kind": "event",
    "label": "Case photograph",
    "alt": "Gausium Scrubber 75 at Chongqing East Railway Station",
    "caption": "Scrubber 75 at Chongqing East Railway Station, from Gausium’s October 2025 case study.",
    "sourceLabel": "Gausium",
    "fit": "contain"
  },
  "gausium-omnie-beetle-issa-november-2024": {
    "src": "https://mma.prnewswire.com/media/2561751/Gausium_ISSA_North_America_2024.jpg?p=facebook",
    "width": 2592,
    "height": 1357,
    "sourceUrl": "https://www.prnewswire.com/news-releases/gausium-sets-new-trends-in-cleaning-technology-with-next-generation-autonomous-solutions-at-issa-show-north-america-2024-302309939.html",
    "kind": "event",
    "label": "Announcement image",
    "alt": "Gausium Omnie, Beetle and other equipment displayed for ISSA North America 2024",
    "caption": "Official ISSA North America 2024 product showcase: Mobile Water Tank, Phantas Workstation, Phantas, Beetle and Omnie, from left to right.",
    "sourceLabel": "Gausium / PR Newswire",
    "fit": "contain"
  },
  "pudu-100000-robot-production-june-2025": {
    "src": "https://pudu-file-host.oss-cn-beijing.aliyuncs.com/official_website/DSC_8813_2025-06-10_19%3A38%3A06.jpg?x-oss-process=image/resize,w_1000/format,webp",
    "width": 1000,
    "height": 631,
    "sourceUrl": "https://www.pudurobotics.com/about/news/684819d0f78ce700438c715a",
    "kind": "event",
    "label": "Factory photograph",
    "alt": "Pudu Robotics production floor pictured in its June 2025 announcement",
    "caption": "Pudu production floor, from the company’s June 2025 announcement of its 100,000th service robot.",
    "sourceLabel": "Pudu Robotics",
    "fit": "cover"
  },
  "pudu-cc1-pro-launch-may-2025": {
    "src": "/images/brands/pudu-robotics/hero-cc1-pro-retail-cleaning.webp",
    "alt": "PUDU CC1 Pro cleaning a retail aisle",
    "kind": "product",
    "label": "Official product image",
    "caption": "PUDU CC1 Pro. Official product reference image, not a photograph of the launch event.",
    "sourceUrl": "https://cdn.pudutech.com/official-website/product/CC1Pro/S5-1.webp",
    "sourceLabel": "Pudu Robotics",
    "width": 1600,
    "height": 1000,
    "fit": "contain"
  },
  "tennant-2024-results-x6-rovr-february-2025": {
    "src": "/images/brands/tennant/hero-x6-rovr-autonomous-scrubber.webp",
    "alt": "Tennant X6 ROVR autonomous floor scrubber",
    "kind": "product",
    "label": "Official product image",
    "caption": "Tennant X6 ROVR, the model named in the announcement. Official product reference image.",
    "sourceUrl": "https://www.tennantco.com/content/dam/tennant/tennantco/products/machines/scrubber%20walk-behinds/x6-rovr/images/x6-rovr-right.jpg/jcr:content/renditions/cq5dam.web.1280.1280.jpeg",
    "sourceLabel": "Tennant",
    "width": 1600,
    "height": 1000,
    "fit": "contain"
  },
  "nilfisk-eurotier-2026-hot-water-cleaning-preview": {
    "src": "https://www.nilfisk.com/product-images-1920/MH45_06_Front-Right-ps-Original-JLUJHTB.webp",
    "alt": "Nilfisk MH45M-200/960 PAX hot-water pressure washer",
    "width": 1920,
    "height": 2287,
    "kind": "product",
    "label": "Official product image",
    "caption": "Nilfisk MH45M-200/960 PAX. Official product reference linked from the EuroTier announcement.",
    "sourceUrl": "https://www.nilfisk.com/de-de/professional/produkte/hochdruckreiniger/mobile-hochdruckreiniger/mobile-heisswasser-hochdruckreiniger/mittel/mh45m-200-960-pax-400-3-50-eu%2B107147106/",
    "sourceLabel": "Nilfisk",
    "fit": "contain"
  },
  "pudu-european-expansion-local-support-2026": {
    "src": "https://mmx.prnewswire.com/media/MS1987330/20260914052323EDT_image_1.jpg?id=OA2945866&p=twitter",
    "alt": "Pudu robots deployed across European commercial settings",
    "width": 1200,
    "height": 961,
    "kind": "event",
    "label": "Announcement image",
    "caption": "European commercial deployments pictured in Pudu’s September 2026 announcement.",
    "sourceUrl": "https://www.prnewswire.com/news-releases/pudu-robotics-deepens-european-presence-following-ifa-2026-advancing-a-scaled-and-localized-growth-strategy-302877494.html",
    "sourceLabel": "Pudu Robotics / PR Newswire",
    "fit": "contain"
  },
  "dexingtianxia-solar-cleaning-production-september-2026": {
    "src": "https://www.whkfq.gov.cn/xwzx/yw/kfqyw/qnxw/202609/W020260910586114512560_ORIGIN.jpg",
    "alt": "Dexingtianxia cleaning equipment on a solar-panel demonstration line",
    "width": 1080,
    "height": 810,
    "kind": "event",
    "label": "Source photograph",
    "caption": "Dexingtianxia equipment pictured in the original September 2026 production report.",
    "sourceUrl": "https://www.whkfq.gov.cn/xwzx/yw/kfqyw/qnxw/202609/t20260910_2846104.html",
    "sourceLabel": "Wuhan Economic & Technological Development Zone",
    "fit": "contain"
  },
  "xiaomi-mijia-6-max-white-september-2026": {
    "src": "https://img14.360buyimg.com/pop/jfs/t1/510765/31/15565/58920/6a9e8f3fF9b32a5c6/008332032026012f.jpg",
    "alt": "White Xiaomi Mijia Robot Vacuum 6 Max configurations",
    "width": 800,
    "height": 800,
    "kind": "product",
    "label": "Original report image",
    "caption": "White Mijia Robot Vacuum 6 Max configurations in the original September 2026 report. Launch-period promotional pricing is historical.",
    "sourceUrl": "https://www.ithome.com/0/999/647.htm",
    "sourceLabel": "ITHome / JD.com",
    "fit": "contain"
  },
  "gausium-schindler-school-elevator-cleaning-austria": {
    "src": "https://gausium.at/media/lech345f/pressebild-schindler-colab_erweitert.png?cc=0,0.2875951833835446,0,0.23210619247636785&width=2600&height=800&format=webp&quality=90&bgcolor=transparent&rnd=134333368881230000",
    "alt": "Gausium cleaning robot at the Austrian school deployment",
    "width": 2600,
    "height": 800,
    "kind": "event",
    "label": "Case photograph",
    "caption": "Gausium and Schindler school deployment in Austria, from the original case announcement.",
    "sourceUrl": "https://gausium.at/pressemeldungen/premiere-in-osterreich-gausium-reinigungsroboter-faehrt-autonom-mit-dem-schindler-aufzug/",
    "sourceLabel": "Gausium Austria",
    "fit": "contain"
  },
  "pudu-gt-series-commercial-robot-mowers-2026": {
    "src": "https://cdn.pudutech.com/1_26b16ca5f8.webp",
    "alt": "PUDU GT3, GT5 and GT7 commercial robotic mowers",
    "width": 1184,
    "height": 752,
    "kind": "product",
    "label": "Official product image",
    "caption": "PUDU GT3, GT5 and GT7. Official GT-series launch image.",
    "sourceUrl": "https://www.pudurobotics.com/en/news/pudu-robotics-launches-gt-series-robotic-mowers",
    "sourceLabel": "Pudu Robotics",
    "fit": "contain"
  },
  "xiaomi-mijia-7c-china-august-2026": {
    "src": "https://img14.360buyimg.com/pop/jfs/t1/501929/1/12887/88685/6a8d08aeFf0c159eb/00833203203d4f67.jpg",
    "alt": "Xiaomi Mijia Robot Vacuum 7C launch poster",
    "width": 800,
    "height": 800,
    "kind": "product",
    "label": "Original report image",
    "caption": "Mijia Robot Vacuum 7C in the original August 2026 report. Launch-period promotional pricing is historical.",
    "sourceUrl": "https://www.ithome.com/0/994/855.htm",
    "sourceLabel": "ITHome / JD.com",
    "fit": "contain"
  },
  "pudu-et1-small-commercial-spaces-launch-2026": {
    "src": "https://mmx.prnewswire.com/media/MS1968490/20260812063835EDT_video_1.mp4?id=OA2866418&p=thumbnail",
    "alt": "PUDU ET1 compact scrubber-dryer robot launch graphic",
    "width": 512,
    "height": 288,
    "kind": "product",
    "label": "Official product image",
    "caption": "PUDU ET1. Still from the company’s official launch video.",
    "sourceUrl": "https://www.prnewswire.com/news-releases/pudu-robotics-launches-pudu-et1-an-ai-native-compact-scrubber-dryer-robot-for-small-commercial-spaces-302849679.html",
    "sourceLabel": "Pudu Robotics / PR Newswire",
    "fit": "contain"
  },
  "idc-commercial-cleaning-robot-shipments-july-2026": {
    "src": "https://n.sinaimg.cn/spider20260707/0/w2048h1152/20260707/b5a6-a30566ca0749ed563557e3bd1990b2a5.jpg",
    "alt": "IDC chart of 2025 commercial service robot shipments",
    "width": 2048,
    "height": 1152,
    "kind": "event",
    "label": "Source chart",
    "caption": "IDC 2025 commercial service robot shipment chart reproduced in the original July 2026 report.",
    "sourceUrl": "https://finance.sina.com.cn/stock/hkstock/hkstocknews/2026-07-07/doc-inifyeew1410316.shtml",
    "sourceLabel": "IDC / Sina Finance",
    "fit": "contain"
  },
  "rowenta-x-force-battery-us-recall-july-2026": {
    "src": "https://www.cpsc.gov/s3fs-public/styles/recall_product/public/forceflex-1.png?VersionId=Xiya2fJgLzJWTlRRQojCXwI8iXRC1UBy&itok=NuNjz-ew",
    "alt": "Rowenta X-Force Flex vacuum cleaners with the recalled batteries",
    "width": 444,
    "height": 400,
    "kind": "product",
    "label": "Official recall image",
    "caption": "Rowenta X-Force Flex vacuum cleaners pictured in the official July 2026 battery recall.",
    "sourceUrl": "https://www.cpsc.gov/Recalls/2026/Rowenta-Recalls-Cordless-Vacuum-Cleaners-Due-to-Risk-of-Serious-Injury-from-fire-and-Burn-Hazards",
    "sourceLabel": "U.S. Consumer Product Safety Commission",
    "fit": "contain"
  },
  "avc-618-cleaning-appliance-sales-june-2026": {
    "src": "https://img02.mysteelcdn.com/wz/uploaded/steel/2026/06/30/7e12a748f94a46e5b774b7a83fe9fcb0.png",
    "alt": "AVC chart of 2026 618 cleaning-appliance sales",
    "width": 1000,
    "height": 562,
    "kind": "event",
    "label": "Source chart",
    "caption": "AVC 2026 618 cleaning-appliance sales chart reproduced in the original report.",
    "sourceUrl": "https://news.mysteel.com/a/26063014/D626B827C4A67D7E.html",
    "sourceLabel": "AVC / Mysteel",
    "fit": "contain"
  },
  "pudu-shenzhen-robot-serviced-hotel-project-june-2026": {
    "src": "https://i.ytimg.com/vi/nDwZ8Wq_YXw/hqdefault.jpg",
    "alt": "Announcement graphic for the Pudu and Shenzhen CTID robot-serviced hotel project",
    "width": 480,
    "height": 360,
    "kind": "event",
    "label": "Announcement image",
    "caption": "Official announcement graphic for the Pudu and Shenzhen CTID hotel project. Not a photograph of an operating hotel.",
    "sourceUrl": "https://www.prnewswire.com/news-releases/pudu-robotics-and-shenzhen-ctid-co-ltd-launch-the-worlds-first-full-scenario-robot-serviced-hotel-project-302786945.html",
    "sourceLabel": "Pudu Robotics / PR Newswire",
    "fit": "contain"
  },
  "avc-first-quarter-cleaning-market-may-2026": {
    "src": "https://upload.cheaa.com/2026/0514/1778729440212.png",
    "alt": "AVC chart of quarterly cleaning-appliance sales growth",
    "width": 654,
    "height": 352,
    "kind": "event",
    "label": "Source chart",
    "caption": "AVC quarterly cleaning-appliance growth chart reproduced in the original first-quarter 2026 report.",
    "sourceUrl": "https://info.cheaa.com/2026/0521/654933.shtml",
    "sourceLabel": "AVC / CHEAA",
    "fit": "contain"
  },
  "pudu-dallas-us-headquarters-april-2026": {
    "src": "https://cdn.pudutech.com/_3fc018396c.png",
    "alt": "Pudu team at the opening of its Dallas-area U.S. headquarters",
    "width": 1184,
    "height": 752,
    "kind": "event",
    "label": "Opening photograph",
    "caption": "Pudu team at the opening of its Dallas-area U.S. headquarters, April 2026.",
    "sourceUrl": "https://www.pudurobotics.com/en/news/pudu-robotics-inaugurates-us-headquarters-dallas-americas-growth",
    "sourceLabel": "Pudu Robotics",
    "fit": "contain"
  },
  "pudu-bg1-large-scrubber-launch-march-2026": {
    "src": "https://cdn.pudutech.com/1184_752_4230d9196f.png",
    "alt": "PUDU BG1 Series scrubber-dryer robots in the official launch graphic",
    "width": 1776,
    "height": 1128,
    "kind": "product",
    "label": "Official product image",
    "caption": "PUDU BG1 Series. Official launch graphic from March 2026.",
    "sourceUrl": "https://www.pudurobotics.com/news/pudu-robotics-unveils-bg1-series-ai-native-large-scale-cleaning",
    "sourceLabel": "Pudu Robotics",
    "fit": "contain"
  }
};

export const newsCompanyVisuals: Record<string, NewsVisual> = {
  "dyson": {
    "src": "/images/brands/dyson/founder-james-dyson.webp",
    "alt": "Sir James Dyson, founder and chairman of Dyson",
    "width": 720,
    "height": 840,
    "kind": "company",
    "fit": "cover",
    "position": "center top",
    "label": "Company image",
    "caption": "Company background image: Sir James Dyson, founder and chairman of Dyson. The Royal Society / Wikimedia Commons, CC BY-SA 4.0; cropped by World Clean Biz. Not a photograph of this news event.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sir_James_Dyson_CBE_FREng_FRS.jpg",
    "sourceLabel": "The Royal Society / Wikimedia Commons",
    "license": {
      "label": "CC BY-SA 4.0",
      "url": "https://creativecommons.org/licenses/by-sa/4.0/"
    }
  },
  "midea": {
    "src": "/images/blog/midea-appliance-brand-portfolio-cover.webp",
    "alt": "WCB editorial cover: Who Owns Midea? Parent Company, Brands and Manufacturing",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns Midea? Parent Company, Brands and Manufacturing. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-midea-appliances-brand-portfolio",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-midea-appliances-brand-portfolio"
  },
  "electrolux": {
    "src": "/images/blog/electrolux-shareholders-brands-manufacturing-cover.webp",
    "alt": "WCB editorial cover: Who Owns Electrolux? Shareholders, Brands and Manufacturing Explained",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns Electrolux? Shareholders, Brands and Manufacturing Explained. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-electrolux-brands-manufacturing",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-electrolux-brands-manufacturing"
  },
  "roborock": {
    "src": "/images/blog/wcb-episode-04-roborock-headquarters.webp",
    "alt": "Roborock headquarters building in China",
    "width": 1600,
    "height": 900,
    "kind": "company",
    "prepared": true,
    "fit": "cover",
    "label": "Company image",
    "caption": "Company background image: Roborock headquarters building in China, from WCB’s founder journal. Not a photograph of this news event.",
    "sourceUrl": "/blog/building-worlds-no-1-cleaning-show-from-scratch-episode-04",
    "sourceLabel": "WCB founder journal"
  },
  "dreame": {
    "src": "/images/brands/dreame/founder-yu-hao.webp",
    "alt": "Yu Hao, founder and CEO of Dreame, holding a high-speed motor component",
    "width": 720,
    "height": 840,
    "kind": "company",
    "fit": "cover",
    "position": "center 20%",
    "label": "Company image",
    "caption": "Company background image: Yu Hao, founder and CEO of Dreame, holding a high-speed motor component. Dreame, via The Wire China; cropped by World Clean Biz. Not a photograph of this news event.",
    "sourceUrl": "https://www.thewirechina.com/2026/06/28/mr-yus-dream-machine/",
    "sourceLabel": "Dreame, via The Wire China"
  },
  "ecovacs": {
    "src": "/images/brands/ecovacs/founder-qian-dongqi.webp",
    "alt": "Qian Dongqi, founder and chairman of ECOVACS",
    "width": 720,
    "height": 840,
    "kind": "company",
    "fit": "cover",
    "position": "center 20%",
    "label": "Company image",
    "caption": "Company background image: Qian Dongqi, founder and chairman of ECOVACS. Shanghai Securities News / CNStock; cropped by World Clean Biz. Not a photograph of this news event.",
    "sourceUrl": "https://company.cnstock.com/company/scp_gsxw/202205/4885270.htm",
    "sourceLabel": "Shanghai Securities News / CNStock"
  },
  "mova": {
    "src": "/images/blog/mova-robot-mower-dreame-group-cover.webp",
    "alt": "WCB editorial cover: Who Owns MOVA? Dreame Group, Country of Origin & Mowers",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns MOVA? Dreame Group, Country of Origin & Mowers. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-makes-mova-robot-mowers-dreame-group",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-makes-mova-robot-mowers-dreame-group"
  },
  "karcher": {
    "src": "/images/blog/who-owns-karcher-family-cover.webp",
    "alt": "WCB editorial cover: Who Owns Kärcher? Family Ownership, Origin and Factories",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns Kärcher? Family Ownership, Origin and Factories. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-karcher-family-professional-cleaning-network",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-karcher-family-professional-cleaning-network"
  },
  "tineco": {
    "src": "/images/brands/tineco/founder-qian-dongqi.webp",
    "alt": "Qian Dongqi, founder of Tineco",
    "width": 720,
    "height": 840,
    "kind": "company",
    "fit": "cover",
    "position": "center 20%",
    "label": "Company image",
    "caption": "Company background image: Qian Dongqi, founder of Tineco. Shanghai Securities News / CNStock; cropped by World Clean Biz. Not a photograph of this news event.",
    "sourceUrl": "https://company.cnstock.com/company/scp_gsxw/202205/4885270.htm",
    "sourceLabel": "Shanghai Securities News / CNStock"
  },
  "shark": {
    "src": "/images/blog/who-owns-sharkninja-js-global-joyoung-cover.webp",
    "alt": "WCB editorial cover: Who Owns SharkNinja? The Real Relationship Between JS Global, Joyoung and SharkNinja",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns SharkNinja? The Real Relationship Between JS Global, Joyoung and SharkNinja. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-sharkninja-js-global-joyoung",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-sharkninja-js-global-joyoung"
  },
  "bosch-home-appliances": {
    "src": "/images/blog/who-owns-bosch-appliances-cover.webp",
    "alt": "WCB editorial cover: Who Owns Bosch Appliances? BSH and Siemens Explained",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns Bosch Appliances? BSH and Siemens Explained. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-bosch-appliances-bsh-siemens-brands",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-bosch-appliances-bsh-siemens-brands"
  },
  "hilti": {
    "src": "/images/blog/hilti-family-trust-manufacturing-cover.webp",
    "alt": "WCB editorial cover: Who Owns Hilti? Family Trust, Manufacturing and Direct-Sales Model Explained",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns Hilti? Family Trust, Manufacturing and Direct-Sales Model Explained. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-hilti-family-trust-manufacturing",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-hilti-family-trust-manufacturing"
  },
  "bissell": {
    "src": "/images/blog/who-owns-bissell-family-sanitaire-cover.webp",
    "alt": "WCB editorial cover: Who Owns BISSELL? Family Ownership & Sanitaire",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns BISSELL? Family Ownership & Sanitaire. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-bissell-family-sanitaire",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-bissell-family-sanitaire"
  },
  "husqvarna": {
    "src": "/images/blog/husqvarna-automower-ownership-map-cover.webp",
    "alt": "WCB editorial cover: Who Owns Husqvarna? Automower, Motorcycles and Manufacturing Explained",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns Husqvarna? Automower, Motorcycles and Manufacturing Explained. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-husqvarna-automower-motorcycles",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-husqvarna-automower-motorcycles"
  },
  "irobot": {
    "src": "/images/brands/irobot/leader-gary-cohen.webp",
    "alt": "Gary Cohen, chief executive officer of iRobot",
    "width": 720,
    "height": 840,
    "kind": "company",
    "fit": "cover",
    "position": "center 20%",
    "label": "Company image",
    "caption": "Company background image: Gary Cohen, chief executive officer of iRobot. iRobot via PR Newswire; cropped by World Clean Biz. Not a photograph of this news event.",
    "sourceUrl": "https://www.prnewswire.com/news-releases/irobot-names-gary-cohen-as-new-chief-executive-officer-302138536.html",
    "sourceLabel": "iRobot via PR Newswire"
  },
  "aiper": {
    "src": "/images/brands/aiper/founder-richard-wang.webp",
    "alt": "Richard Wang, founder and CEO of Aiper, at the Aiper and Fluidra signing ceremony",
    "width": 720,
    "height": 840,
    "kind": "company",
    "fit": "cover",
    "position": "center 20%",
    "label": "Company image",
    "caption": "Company background image: Richard Wang, founder and CEO of Aiper, at the Aiper and Fluidra signing ceremony. Aiper, via PR Newswire; cropped by World Clean Biz. Not a photograph of this news event.",
    "sourceUrl": "https://www.prnewswire.com/apac/news-releases/aiper-launches-global-strategic-hub-in-singapore-following-usd-100-million-strategic-investment-from-fluidra-302469142.html",
    "sourceLabel": "Aiper, via PR Newswire"
  },
  "eufy": {
    "src": "/images/blog/who-owns-eufy-anker-smart-home-cover.webp",
    "alt": "WCB editorial cover: Who Owns Eufy? How Anker Built a Smart-Home Brand Beyond Robot Vacuums",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns Eufy? How Anker Built a Smart-Home Brand Beyond Robot Vacuums. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-eufy-anker-smart-home",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-eufy-anker-smart-home"
  },
  "narwal": {
    "src": "/images/blog/who-owns-narwal-cover.webp",
    "alt": "WCB editorial cover: Who Owns Narwal? Yunjing, Its Investors and Manufacturing Network Explained",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns Narwal? Yunjing, Its Investors and Manufacturing Network Explained. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-narwal-yunjing-investors-manufacturing",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-narwal-yunjing-investors-manufacturing"
  },
  "ge-appliances": {
    "src": "/images/blog/ge-appliances-haier-manufacturing-cover.webp",
    "alt": "WCB editorial cover: Who Owns GE Appliances? Haier, U.S. Manufacturing and the Brand Portfolio Explained",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns GE Appliances? Haier, U.S. Manufacturing and the Brand Portfolio Explained. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-ge-appliances-haier-manufacturing",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-ge-appliances-haier-manufacturing"
  },
  "haier-home-appliances": {
    "src": "/images/blog/haier-smart-home-brand-portfolio-cover.webp",
    "alt": "WCB editorial cover: Who Owns Haier Appliances? Haier Smart Home, GE Appliances, Candy and Fisher & Paykel Explained",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns Haier Appliances? Haier Smart Home, GE Appliances, Candy and Fisher & Paykel Explained. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-haier-appliances-brand-portfolio",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-haier-appliances-brand-portfolio"
  },
  "greenworks": {
    "src": "/images/blog/greenworks-ownership-cover.webp",
    "alt": "WCB editorial cover: Who Owns Greenworks? Globe Tools, STIHL and Manufacturing Explained",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns Greenworks? Globe Tools, STIHL and Manufacturing Explained. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-greenworks-globe-stihl",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-greenworks-globe-stihl"
  },
  "philips-home-appliances": {
    "src": "/images/blog/philips-versuni-ownership-cover.webp",
    "alt": "WCB editorial cover: Who Makes Philips Vacuums? Versuni Ownership Explained",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Makes Philips Vacuums? Versuni Ownership Explained. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-makes-philips-vacuum-cleaners-versuni",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-makes-philips-vacuum-cleaners-versuni"
  },
  "flex": {
    "src": "/images/blog/flex-chervon-lowes-cover.webp",
    "alt": "WCB editorial cover: Who Owns FLEX Tools? Chervon, Lowe's Distribution and Manufacturing Explained",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns FLEX Tools? Chervon, Lowe's Distribution and Manufacturing Explained. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-flex-tools-chervon-lowes",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-flex-tools-chervon-lowes"
  },
  "skil": {
    "src": "/images/blog/skil-chervon-history-cover.webp",
    "alt": "WCB editorial cover: Who Owns SKIL Tools? Chervon, Bosch History and Manufacturing Explained",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns SKIL Tools? Chervon, Bosch History and Manufacturing Explained. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-skil-tools-chervon",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-skil-tools-chervon"
  },
  "milwaukee": {
    "src": "/images/blog/milwaukee-ownership-cover.webp",
    "alt": "WCB editorial cover: Who Owns Milwaukee Tools? TTI and Where They Are Made",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns Milwaukee Tools? TTI and Where They Are Made. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-milwaukee-tools-tti-manufacturing",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-milwaukee-tools-tti-manufacturing"
  },
  "dewalt": {
    "src": "/images/blog/dewalt-ownership-cover.webp",
    "alt": "WCB editorial cover: Who Owns DeWalt? Stanley Black & Decker and Manufacturing Explained",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns DeWalt? Stanley Black & Decker and Manufacturing Explained. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-dewalt-stanley-black-decker",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-dewalt-stanley-black-decker"
  },
  "segway-navimow": {
    "src": "/images/blog/segway-navimow-ninebot-willand-ownership-cover.webp",
    "alt": "WCB editorial cover: Who Owns Segway Navimow? Ninebot, Willand and Manufacturing",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns Segway Navimow? Ninebot, Willand and Manufacturing. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-segway-navimow-ninebot-willand",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-segway-navimow-ninebot-willand"
  },
  "ryobi": {
    "src": "/images/blog/ryobi-ownership-cover.webp",
    "alt": "WCB editorial cover: Who Owns Ryobi? Ryobi Limited, TTI and Kyocera Explained",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns Ryobi? Ryobi Limited, TTI and Kyocera Explained. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-ryobi-tti-kyocera",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-ryobi-tti-kyocera"
  },
  "hoover": {
    "src": "/images/blog/who-owns-hoover-tti-haier-candy-cover.webp",
    "alt": "WCB editorial cover: Who Owns Hoover? TTI, Haier and the Brand's Regional Split Explained",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns Hoover? TTI, Haier and the Brand's Regional Split Explained. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-hoover-tti-haier-candy",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-hoover-tti-haier-candy"
  },
  "whirlpool": {
    "src": "/images/blog/whirlpool-beko-europe-ownership-cover.webp",
    "alt": "WCB editorial cover: Who Owns Whirlpool Appliances? Whirlpool Corporation, Beko Europe and Regional Brand Rights Explained",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns Whirlpool Appliances? Whirlpool Corporation, Beko Europe and Regional Brand Rights Explained. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-whirlpool-appliances-beko-europe",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-whirlpool-appliances-beko-europe"
  },
  "makita": {
    "src": "/images/blog/makita-ownership-cover.webp",
    "alt": "WCB editorial cover: Who Owns Makita? Public Company, Manufacturing Network and Battery Platforms Explained",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns Makita? Public Company, Manufacturing Network and Battery Platforms Explained. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-makita-company-manufacturing",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-makita-company-manufacturing"
  },
  "black-decker": {
    "src": "/images/blog/black-decker-stanley-ownership-manufacturing-map.webp",
    "alt": "WCB editorial cover: Who Owns BLACK+DECKER? Stanley Black & Decker Explained",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns BLACK+DECKER? Stanley Black & Decker Explained. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-black-and-decker-stanley-tools",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-black-and-decker-stanley-tools"
  },
  "craftsman": {
    "src": "/images/blog/craftsman-ownership-cover.webp",
    "alt": "WCB editorial cover: Who Owns Craftsman Tools? Stanley Black & Decker, Lowe's and Manufacturing Explained",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns Craftsman Tools? Stanley Black & Decker, Lowe's and Manufacturing Explained. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-craftsman-tools-stanley-black-decker",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-craftsman-tools-stanley-black-decker"
  },
  "lg-home-appliances": {
    "src": "/images/blog/lg-appliances-manufacturing-network-cover.webp",
    "alt": "WCB editorial cover: Who Makes LG Appliances? LG Electronics, Manufacturing Network and Home Appliance Business Explained",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Makes LG Appliances? LG Electronics, Manufacturing Network and Home Appliance Business Explained. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-makes-lg-appliances-manufacturing-network",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-makes-lg-appliances-manufacturing-network"
  },
  "sunseeker": {
    "src": "/images/blog/sunseeker-robot-mower-company-manufacturer-cover.webp",
    "alt": "WCB editorial cover: Who Makes Sunseeker Robot Mowers? Zhejiang Sunseeker",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Makes Sunseeker Robot Mowers? Zhejiang Sunseeker. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-makes-sunseeker-robot-mowers-zhejiang-sunseeker",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-makes-sunseeker-robot-mowers-zhejiang-sunseeker"
  },
  "mammotion": {
    "src": "/images/brands/mammotion/founder-jidong-wei.webp",
    "alt": "Jidong (Jayden) Wei, founder and CEO of Mammotion",
    "width": 720,
    "height": 840,
    "kind": "company",
    "fit": "cover",
    "position": "center 20%",
    "label": "Company image",
    "caption": "Company background image: Jidong (Jayden) Wei, founder and CEO of Mammotion. Green Industry Pros; cropped by World Clean Biz. Not a photograph of this news event.",
    "sourceUrl": "https://www.greenindustrypros.com/mowing-maintenance/contact/22340213/jidong-wei",
    "sourceLabel": "Green Industry Pros"
  },
  "wybot": {
    "src": "/images/blog/wybot-wybotics-wangyuan-manufacturer-cover.webp",
    "alt": "WCB editorial cover: Who Makes WYBOT Pool Cleaners? WYBOTICS and Made in China",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Makes WYBOT Pool Cleaners? WYBOTICS and Made in China. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-makes-wybot-pool-cleaners-wybotics-wangyuan",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-makes-wybot-pool-cleaners-wybotics-wangyuan"
  },
  "beatbot": {
    "src": "/images/blog/beatbot-xingmai-ownership-cover.webp",
    "alt": "WCB editorial cover: Who Owns Beatbot? Xingmai and Where Its Cleaners Are Made",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns Beatbot? Xingmai and Where Its Cleaners Are Made. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-beatbot-xingmai-manufacturing",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-beatbot-xingmai-manufacturing"
  },
  "samsung-home-appliances": {
    "src": "/images/blog/samsung-appliances-global-network-cover.webp",
    "alt": "WCB editorial cover: Who Makes Samsung Appliances? Samsung Electronics, Global Manufacturing and Bespoke AI Explained",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Makes Samsung Appliances? Samsung Electronics, Global Manufacturing and Bespoke AI Explained. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-makes-samsung-appliances-manufacturing-bespoke-ai",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-makes-samsung-appliances-manufacturing-bespoke-ai"
  },
  "worx": {
    "src": "/images/blog/worx-positec-landroid-ownership-map-cover.webp",
    "alt": "WCB editorial cover: Who Owns WORX? Positec, Landroid and Manufacturing Explained",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns WORX? Positec, Landroid and Manufacturing Explained. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-worx-positec-landroid-manufacturing",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-worx-positec-landroid-manufacturing"
  },
  "metabo": {
    "src": "/images/blog/metabo-hpt-hikoki-ownership-cover.webp",
    "alt": "WCB editorial cover: Metabo vs Metabo HPT: Ownership, HiKOKI and Batteries",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Metabo vs Metabo HPT: Ownership, HiKOKI and Batteries. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-metabo-metabo-hpt-hikoki",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-metabo-metabo-hpt-hikoki"
  },
  "hikoki": {
    "src": "/images/blog/metabo-hpt-hikoki-ownership-cover.webp",
    "alt": "WCB editorial cover: Metabo vs Metabo HPT: Ownership, HiKOKI and Batteries",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Metabo vs Metabo HPT: Ownership, HiKOKI and Batteries. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-metabo-metabo-hpt-hikoki",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-metabo-metabo-hpt-hikoki"
  },
  "oreck": {
    "src": "/images/blog/who-owns-tti-cover.webp",
    "alt": "WCB editorial cover: Who Owns TTI? Milwaukee, Ryobi, Hoover, Vax and Oreck Explained",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns TTI? Milwaukee, Ryobi, Hoover, Vax and Oreck Explained. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-tti-milwaukee-ryobi-hoover-vax-oreck",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-tti-milwaukee-ryobi-hoover-vax-oreck"
  },
  "dirt-devil": {
    "src": "/images/blog/who-owns-tti-cover.webp",
    "alt": "WCB editorial cover: Who Owns TTI? Milwaukee, Ryobi, Hoover, Vax and Oreck Explained",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns TTI? Milwaukee, Ryobi, Hoover, Vax and Oreck Explained. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-tti-milwaukee-ryobi-hoover-vax-oreck",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-tti-milwaukee-ryobi-hoover-vax-oreck"
  },
  "fluidra": {
    "src": "/images/blog/polaris-fluidra-zodiac-ownership-cover.webp",
    "alt": "WCB editorial cover: Who Owns Polaris Pool Cleaners? Fluidra & Zodiac",
    "width": 1600,
    "height": 900,
    "kind": "coverage",
    "fit": "contain",
    "prepared": true,
    "label": "Related coverage",
    "caption": "Related coverage: Who Owns Polaris Pool Cleaners? Fluidra & Zodiac. Editorial cover, not a photograph of this news event.",
    "sourceUrl": "/blog/who-owns-polaris-pool-cleaners-fluidra-zodiac",
    "sourceLabel": "Read the related coverage",
    "relatedArticleSlug": "who-owns-polaris-pool-cleaners-fluidra-zodiac"
  },
  "fiorentini": {
    "src": "/images/brands/fiorentini/hero-production-floor.webp",
    "alt": "Fiorentini production worker operating moulding equipment at an Italian factory",
    "width": 1600,
    "height": 1000,
    "kind": "company",
    "fit": "cover",
    "label": "Company image",
    "caption": "Official Fiorentini production photo showing an operator and industrial moulding equipment. Company context, not a photograph of this news event.",
    "sourceUrl": "/brands/fiorentini",
    "sourceLabel": "Company profile and sources"
  },
  "pudu-robotics": {
    "src": "https://pudu-file-host.oss-cn-beijing.aliyuncs.com/official_website/DSC_8813_2025-06-10_19%3A38%3A06.jpg?x-oss-process=image/resize,w_1000/format,webp",
    "width": 1000,
    "height": 631,
    "sourceUrl": "https://www.pudurobotics.com/about/news/684819d0f78ce700438c715a",
    "kind": "company",
    "label": "Company image",
    "alt": "Pudu Robotics production floor pictured in its June 2025 announcement",
    "caption": "Company background: Pudu production floor, photographed for its June 2025 announcement. Not a photograph of this news event.",
    "sourceLabel": "Pudu Robotics",
    "fit": "cover"
  }
};

/** WCB-owned archive context for news with no verified story or company photograph. */
export const newsIndustryContextVisual: NewsVisual = {
  src: "/images/industry/about-forum-audience-2025.jpg",
  alt: "Audience at a WCB industry gathering in 2025",
  width: 2200,
  height: 1467,
  kind: "context",
  fit: "cover",
  label: "Industry context",
  caption: "WCB 2025 industry gathering archive photograph. Industry context only; not a photograph of this news event.",
  sourceUrl: "/images/industry/about-forum-audience-2025.jpg",
  sourceLabel: "World Clean Biz · 2025 event archive"
};
