export type ProductDirection = {
  id: string;
  name: string;
  positioning: string;
  lawnContext: string;
  markets: string[];
  channels: string[];
  technologyDirection: string;
  opportunity: string;
  verificationRisk: string;
  image: string;
  imageAlt: string;
};

export type SourcingProduct = {
  slug: "lawn-robots" | "pool-robots" | "floor-washers" | "robotic-vacuums";
  productCategory: string;
  title: string;
  metaDescription: string;
  eyebrow: string;
  intro: string;
  buyerProblems: string[];
  services: string[];
  evaluationPoints: string[];
  marketNotes: string[];
  relatedArticleSlugs: string[];
  image: string;
  imageAlt: string;
  directions?: ProductDirection[];
};

export const sourcingProducts: Record<SourcingProduct["slug"], SourcingProduct> = {
  "robotic-vacuums": {
    slug: "robotic-vacuums",
    productCategory: "robot_vacuum",
    title: "Robot Vacuum Manufacturers & Sourcing in China",
    metaDescription: "Evaluate robot vacuum manufacturers in China through product opportunity, supplier capability, platform proof points and after-sales economics.",
    eyebrow: "Robot Vacuum Sourcing",
    intro: "Robot vacuum competition is no longer decided by suction figures alone. Navigation, obstacle handling, dock systems, mopping, app stability and after-sales readiness determine whether a platform can sustain a target market and channel.",
    buyerProblems: ["Similar specifications can hide major navigation and ownership differences", "Docks, water systems and software can turn a product decision into a warranty decision", "Retail and ecommerce require a clear household story, not an undifferentiated flagship", "A product sample does not prove long-term service economics"],
    services: ["Category and product opportunity review", "Manufacturer discovery and capability screening", "Specification, sample and differentiation review", "Quality-risk and execution support before production"],
    evaluationPoints: ["Navigation, obstacle avoidance and map recovery", "Pickup, mopping and carpet-treatment performance", "Dock systems, water management and hygiene", "App, firmware and cloud-service readiness", "Testing depth, parts and warranty execution"],
    marketNotes: ["North American launches need a clear position across households, pets, carpets and retail price bands.", "European buyers need product, privacy, compliance and service preparation that fits their chosen channel.", "Premium positioning depends on dependable automated ownership—not only a larger dock or a longer feature list."],
    relatedArticleSlugs: ["how-to-source-robot-vacuum-cleaners-from-china", "roborock-at-a-crossroads", "roborock-channel-shift-online-to-offline-experience"],
    image: "/images/sourcing/robotic-vacuums/rv-02-premium-dock-concept.png",
    imageAlt: "Illustrative premium robot vacuum and self-cleaning dock for product evaluation",
    directions: [
      { id: "RV-01", name: "Retail Navigation Starter", positioning: "A credible first platform for households and retailers entering robot vacuum ownership without flagship complexity.", lawnContext: "Everyday hard floors and simple homes", markets: ["Europe", "North America"], channels: ["Retail", "Ecommerce"], technologyDirection: "LiDAR or structured-navigation consumer platform", opportunity: "A focused cleaning story and dependable setup can make the category more accessible than a feature-heavy flagship.", verificationRisk: "Verify mapping, recovery, pickup, app onboarding and return economics in ordinary homes.", image: "/images/sourcing/robotic-vacuums/rv-01-retail-starter-concept.png", imageAlt: "Illustrative entry robot vacuum with compact dock in a home" },
      { id: "RV-02", name: "All-in-One Premium Platform", positioning: "A high-value automated-cleaning route where dock capability and maintenance convenience support a premium price.", lawnContext: "Premium multi-room homes", markets: ["United States", "Europe"], channels: ["Specialist dealer", "Premium retail"], technologyDirection: "Self-washing, drying and emptying dock", opportunity: "Premium value becomes credible when the dock reduces real daily maintenance, not when it only increases technical complexity.", verificationRisk: "Test dock reliability, leakage, washing and drying hygiene, consumables, water handling and service access.", image: "/images/sourcing/robotic-vacuums/rv-02-premium-dock-concept.png", imageAlt: "Illustrative robot vacuum with all-in-one dock" },
      { id: "RV-03", name: "Low-Profile Reach Platform", positioning: "A differentiated route for homes where low furniture, access and cleaning coverage are a visible ownership problem.", lawnContext: "Low-clearance furniture and urban homes", markets: ["Europe", "Asia-Pacific"], channels: ["Ecommerce", "Specialist retail"], technologyDirection: "Low-profile navigation architecture", opportunity: "Visible under-furniture coverage creates a compelling reason to switch when it is proven without weakening navigation.", verificationRisk: "Verify clearance, navigation accuracy, obstacle handling, map stability and cleaning performance in low-light areas.", image: "/images/sourcing/robotic-vacuums/rv-03-low-profile-concept.png", imageAlt: "Illustrative low-profile robot vacuum cleaning under a sofa" },
      { id: "RV-04", name: "Pet and Carpet Specialist", positioning: "A performance-led platform for households that need reliable hair handling and carpet cleaning rather than a generic robot.", lawnContext: "Pets, rugs and mixed floors", markets: ["North America", "Europe"], channels: ["Specialist dealer", "Ecommerce"], technologyDirection: "Hair-management and carpet-treatment platform", opportunity: "Pet hair and rugs create a visible problem that can support a more focused product and channel story.", verificationRisk: "Prove hair pickup, brush anti-tangle, carpet behaviour, noise, bin capacity and customer maintenance.", image: "/images/sourcing/robotic-vacuums/rv-04-pet-carpet-concept.png", imageAlt: "Illustrative robot vacuum for pet hair and carpet cleaning" },
      { id: "RV-05", name: "Ecommerce Value Platform", positioning: "A concise online-first platform that combines a clear use case with controlled logistics and support demand.", lawnContext: "Compact apartments and first-time buyers", markets: ["North America", "Europe"], channels: ["Ecommerce", "Private label"], technologyDirection: "Compact value robot vacuum platform", opportunity: "A narrow promise can reduce the education burden and make online category entry more manageable.", verificationRisk: "Verify packaging, setup completion, support demand, parts availability and returns before committing to volume.", image: "/images/sourcing/robotic-vacuums/rv-05-ecommerce-value-concept.png", imageAlt: "Illustrative ecommerce robot vacuum in a compact apartment" },
      { id: "RV-06", name: "Edge-Cleaning Premium Platform", positioning: "A high-value route for buyers who need a visible cleaning result at walls, corners and kitchen edges.", lawnContext: "Finished floors and detailed-edge cleaning", markets: ["Europe", "Middle East", "North America"], channels: ["Premium retail", "Specialist dealer"], technologyDirection: "Extending side brush or mop architecture", opportunity: "A demonstrable edge-cleaning result can create a sharper trade-up reason than a marginal suction claim.", verificationRisk: "Test arm durability, edge coverage, furniture interaction, water management and repairability under repeated use.", image: "/images/sourcing/robotic-vacuums/rv-06-edge-cleaning-concept.png", imageAlt: "Illustrative premium robot vacuum cleaning along a kitchen edge" }
    ]
  },
  "floor-washers": {
    slug: "floor-washers",
    productCategory: "hard_floor_washer",
    title: "Hard Floor Washer Manufacturers & Sourcing in China",
    metaDescription: "Evaluate hard floor washer manufacturers in China with support for product direction, supplier screening, sampling, quality-risk review and execution.",
    eyebrow: "Hard Floor Washer Sourcing",
    intro: "Hard floor washers are expanding beyond their early China-led adoption, but cleaning performance, self-cleaning, battery behaviour, leakage control and after-sales cost determine whether a product can scale in a target channel.",
    buyerProblems: ["Similar specifications can hide major real-world cleaning differences", "Battery, dirty-water and self-cleaning systems create warranty risk", "Retail and ecommerce need a simple ownership story, not a feature list", "Roller, tank and consumable economics can reshape the margin after launch"],
    services: ["Category and product opportunity review", "Manufacturer discovery and capability screening", "Specification, sample and differentiation review", "Quality-risk and execution support before production"],
    evaluationPoints: ["Wet cleaning, pickup and edge performance", "Self-cleaning, drying and odor-control behaviour", "Battery, water tank, roller and leakage reliability", "Testing depth and production consistency", "Consumables, warranty and replacement-parts readiness"],
    marketNotes: ["North American buyers need a clear use case against mops, vacuums and established floorcare routines.", "European and UK launches need channel-specific positioning, compliance and service preparation.", "Premium positioning depends on ownership convenience and durable performance, not the number of cleaning modes."],
    relatedArticleSlugs: ["floor-washer-manufacturers-china", "story-of-hard-floor-washers", "laifen-hard-floor-washer-entry-strategy"],
    image: "/images/sourcing/floor-washers/fw-02-cordless-premium-concept.png",
    imageAlt: "Illustrative cordless hard floor washer for product and supplier evaluation",
    directions: [
      { id: "FW-01", name: "Retail Wet-Clean Starter", positioning: "A clear, approachable platform for first-time wet-cleaning buyers and retailers opening the category.", lawnContext: "Everyday kitchens and compact homes", markets: ["Europe", "North America"], channels: ["Retail", "Ecommerce"], technologyDirection: "Corded or entry cordless roller platform", opportunity: "A focused first-use story can make the category easier to explain than a broad premium feature list.", verificationRisk: "Verify pickup, streaking, tank handling, roller care and return economics with normal household messes.", image: "/images/sourcing/floor-washers/fw-01-corded-kitchen-concept.png", imageAlt: "Illustrative hard floor washer for a bright residential kitchen" },
      { id: "FW-02", name: "Cordless Premium Platform", positioning: "A higher-value cordless route where mobility, edge cleaning and low-friction ownership justify a trade-up.", lawnContext: "Multi-room homes and premium floorcare", markets: ["United States", "Europe"], channels: ["Specialist retail", "Direct-to-consumer"], technologyDirection: "Cordless roller washer with dock", opportunity: "Premium pricing becomes credible when the product removes real cleaning and maintenance friction.", verificationRisk: "Test runtime under wet load, edge reach, tank seals, battery ageing and cleaning performance across floor types.", image: "/images/sourcing/floor-washers/fw-02-cordless-premium-concept.png", imageAlt: "Illustrative premium cordless hard floor washer with charging dock" },
      { id: "FW-03", name: "Deep-Clean Design Platform", positioning: "A design-led platform for buyers who need visible cleaning performance in premium residential channels.", lawnContext: "Polished tile and finished hard floors", markets: ["Europe", "Middle East"], channels: ["Specialist dealer", "Premium retail"], technologyDirection: "High-visibility roller and water-control system", opportunity: "A premium product can win when results, handling and product design create a visible reason to choose it.", verificationRisk: "Prove roller coverage, water dosing, marks after drying, noise, hygiene and serviceability—not just appearance.", image: "/images/sourcing/floor-washers/fw-03-premium-hallway-concept.png", imageAlt: "Illustrative premium hard floor washer on polished tile" },
      { id: "FW-04", name: "Ecommerce Value Platform", positioning: "A concise online-first offer built around a clear mess, a visible result and manageable ownership expectations.", lawnContext: "Urban homes and frequent kitchen spills", markets: ["North America", "Europe"], channels: ["Ecommerce", "Private label"], technologyDirection: "Compact cordless value architecture", opportunity: "A narrow use case can lower the education burden while preserving a credible reason to buy online.", verificationRisk: "Verify packaging resilience, onboarding, customer support demand, replacement consumables and returns before volume.", image: "/images/sourcing/floor-washers/fw-04-ecommerce-spill-concept.png", imageAlt: "Illustrative compact hard floor washer cleaning a kitchen spill" },
      { id: "FW-05", name: "Light-Commercial Service Platform", positioning: "A durable route for boutique hospitality and small professional environments where uptime and recovery matter.", lawnContext: "Hotels, clinics and high-use hard floors", markets: ["Europe", "Middle East", "North America"], channels: ["Professional / project sales", "Specialist dealer"], technologyDirection: "High-capacity recovery and service platform", opportunity: "Higher value is possible when the platform reduces manual steps and supports predictable service in high-use sites.", verificationRisk: "Verify duty cycle, recovery capacity, component durability, field repair and parts availability before scaling.", image: "/images/sourcing/floor-washers/fw-05-commercial-concept.png", imageAlt: "Illustrative professional hard floor washer in a hospitality service area" },
      { id: "FW-06", name: "Self-Cleaning Convenience Platform", positioning: "A premium ownership platform built around cleaner maintenance, docking and repeat use after the sale.", lawnContext: "Convenience-led households", markets: ["United States", "Europe", "Asia-Pacific"], channels: ["Ecommerce", "Premium retail"], technologyDirection: "Self-cleaning and drying dock architecture", opportunity: "A stronger maintenance story can support repeat use and a premium position when it is genuinely reliable.", verificationRisk: "Test self-cleaning completion, drying hygiene, odour control, dock leakage, consumable wear and customer maintenance steps.", image: "/images/sourcing/floor-washers/fw-06-self-cleaning-dock-concept.png", imageAlt: "Illustrative cordless hard floor washer on a self-cleaning dock" }
    ]
  },
  "lawn-robots": {
    slug: "lawn-robots",
    productCategory: "robotic_lawn_mower",
    title: "Robotic Lawn Mower Manufacturers & Sourcing in China",
    metaDescription: "Find and evaluate robotic lawn mower manufacturers in China with support for supplier matching, product direction, sampling, quality risk and execution.",
    eyebrow: "Robotic Lawn Mower Sourcing",
    intro: "The category is expanding quickly, but navigation systems, terrain performance, installation, safety and after-sales readiness vary widely. World Clean Biz helps buyers evaluate the product and the supplier behind it.",
    buyerProblems: ["Too many suppliers present similar specifications", "Real-world terrain performance is difficult to compare", "Installation and after-sales requirements differ by market", "A fast-moving category can make product decisions obsolete quickly"],
    services: ["Product direction and supplier landscape review", "Manufacturer discovery and capability screening", "Specification, sample and differentiation review", "Quality-risk and execution support before production"],
    evaluationPoints: ["Navigation and boundary technology", "Slope, obstacle and terrain performance", "Safety, weather resistance and theft protection", "App stability, installation and service readiness", "Production experience, testing and spare-parts support"],
    marketNotes: ["North American buyers need products suited to larger and more varied lawns.", "European and UK buyers often place greater weight on installation, safety, noise and channel service.", "A global launch plan should separate market requirements instead of using one specification everywhere."],
    relatedArticleSlugs: ["robotic-lawn-mower-manufacturers-china", "robotic-mowers-2026-breakthrough", "amazon-first-stop-for-backyard-robotics"],
    image: "/images/sourcing/lawn-robots.png",
    imageAlt: "Robotic lawn mower sourcing and manufacturer evaluation",
    directions: [
      { id: "RM-01", name: "Mass-Market Vision", positioning: "An installation-light platform for smaller lawns, first-time robotic mower buyers and channels that cannot depend on professional setup.", lawnContext: "Small residential lawns", markets: ["UK", "Europe"], channels: ["Retail", "Ecommerce"], technologyDirection: "Camera-led navigation for mass adoption", opportunity: "Removing the boundary-wire visit can open robotic mowing beyond early adopters and premium dealer channels.", verificationRisk: "Prove edge cutting, obstacle recognition, changing-light performance and consumer-led setup in ordinary gardens.", image: "/images/sourcing/lawn-robots/rm-01-compact-vision.png", imageAlt: "Concept compact vision robotic lawn mower on a small residential lawn" },
      { id: "RM-02", name: "RTK Step-Up", positioning: "A higher-value, boundary-free platform for medium and larger lawns where coverage and zone control justify a step up from entry products.", lawnContext: "Medium to large open lawns", markets: ["United States", "Europe"], channels: ["Specialist retail", "Direct-to-consumer"], technologyDirection: "RTK positioning with supporting sensors", opportunity: "RTK earns a premium when larger-area coverage, editable zones and faster installation are visible to the customer.", verificationRisk: "Test signal loss, tree and building interference, map recovery, antenna placement and the complete installation journey.", image: "/images/sourcing/lawn-robots/rm-02-rtk-platform.png", imageAlt: "Concept RTK robotic lawn mower on a large residential lawn" },
      { id: "RM-03", name: "AWD Terrain Specialist", positioning: "A premium platform for sloped, uneven gardens that standard robotic mowers struggle to serve consistently.", lawnContext: "Slopes and complex terrain", markets: ["Europe", "North America"], channels: ["Premium dealers", "Specialist ecommerce"], technologyDirection: "Four-wheel-drive mobility platform", opportunity: "Terrain capability solves a visible problem and gives dealers a stronger trade-up story than marginal specification gains.", verificationRisk: "Require evidence for usable slope performance, rollover safety, turf protection, wet-ground behavior and drivetrain durability.", image: "/images/sourcing/lawn-robots/rm-03-awd-slope.png", imageAlt: "Concept all-wheel-drive robotic lawn mower on sloped terrain" },
      { id: "RM-04", name: "Proven Value Platform", positioning: "A mature boundary-wire route for buyers competing on dependable mowing and controlled product cost rather than installation novelty.", lawnContext: "Simple lawns with planned installation", markets: ["Europe", "Value-led markets"], channels: ["Mass retail", "Private label"], technologyDirection: "Established boundary-wire architecture", opportunity: "Predictable operation and accessible pricing can matter more than eliminating the initial installation step.", verificationRisk: "Model installation support, app quality, repairability, spare parts, returns and service cost—not only the factory quotation.", image: "/images/sourcing/lawn-robots/rm-04-value-wire.png", imageAlt: "Concept value boundary-wire robotic lawn mower in a suburban garden" },
      { id: "RM-05", name: "Large-Area Service Platform", positioning: "A professional route for estates and maintained grounds where coverage, uptime and service support matter most.", lawnContext: "Estates and maintained grounds", markets: ["United States", "Europe"], channels: ["Professional dealers", "Project sales"], technologyDirection: "Large-area multi-sensor platform", opportunity: "Higher product and service value is possible when the offer reduces labor and gives operators confidence in uptime.", verificationRisk: "Verify coverage efficiency, remote oversight, multi-zone behavior, field repair, parts lead times and dealer service capability.", image: "/images/sourcing/lawn-robots/rm-05-large-area-professional.png", imageAlt: "Concept professional robotic lawn mower on a large estate lawn" },
      { id: "RM-06", name: "Retail Category Starter", positioning: "A compact platform for testing robotic mowing without the price, logistics and service burden of a flagship model.", lawnContext: "Compact lawns and first-time households", markets: ["UK", "Europe", "Urban markets"], channels: ["Retail", "Ecommerce"], technologyDirection: "Compact consumer retail platform", opportunity: "A focused use case and simpler logistics can lower the retailer's risk of opening the category.", verificationRisk: "Prove mowing quality, setup completion, packaging resilience, return economics and after-sales support; compact cannot mean disposable.", image: "/images/sourcing/lawn-robots/rm-06-compact-retail.png", imageAlt: "Concept compact retail robotic lawn mower in a modern small garden" }
    ]
  },
  "pool-robots": {
    slug: "pool-robots",
    productCategory: "robotic_pool_cleaner",
    title: "Robotic Pool Cleaner Manufacturers & Sourcing in China",
    metaDescription: "Find and evaluate robotic pool cleaner manufacturers in China with support for supplier matching, product direction, sampling, quality risk and execution.",
    eyebrow: "Robotic Pool Cleaner Sourcing",
    intro: "Pool robots are moving into broader retail channels, but cleaning coverage, filtration, waterproof reliability and service capability are not easy to judge from a quotation. World Clean Biz helps buyers compare the complete product and supplier system.",
    buyerProblems: ["Product appearance can hide major performance differences", "Waterproof reliability and long-term durability are hard to validate", "Channel requirements vary across specialist retail and ecommerce", "Parts, warranty and service can determine the real product cost"],
    services: ["Category and product opportunity review", "Manufacturer discovery and capability screening", "Specification, sample and differentiation review", "Quality-risk and execution support before production"],
    evaluationPoints: ["Pool coverage, navigation and wall-climbing performance", "Filtration, debris handling and cleaning-cycle design", "Waterproofing, motors, cables and battery reliability", "Testing standards and production consistency", "Warranty, replacement parts and service readiness"],
    marketNotes: ["North American buyers need clear positioning across pool types, sizes and retail channels.", "European and UK buyers may require different product, compliance and service preparation.", "Premium positioning depends on reliability and ownership experience, not only cleaning specifications."],
    relatedArticleSlugs: ["robotic-pool-cleaner-manufacturers-china", "aiper-fluidra-pool-robotics-alliance", "maytronics-robotic-pool-cleaner-reinvention"],
    image: "/images/sourcing/pool-robots.png",
    imageAlt: "Robotic pool cleaner sourcing and manufacturer evaluation",
    directions: [
      { id: "RM-01", name: "Cordless Retail Starter", positioning: "A simple cordless platform for above-ground pools and first-time robot buyers.", lawnContext: "Above-ground and compact pools", markets: ["North America", "Europe"], channels: ["Retail", "Ecommerce"], technologyDirection: "Cordless consumer platform", opportunity: "A clear entry use case can make pool robotics easier to merchandise than a full-featured premium cleaner.", verificationRisk: "Verify cycle completion, retrieval, filtration, charging safety and return economics in real debris conditions.", image: "/images/sourcing/pool-robots/rm-01-cordless-retail-concept.png", imageAlt: "Illustrative cordless robotic pool cleaner for compact residential pools" },
      { id: "RM-02", name: "Wall-Climbing Step-Up", positioning: "A higher-value platform for in-ground pools where wall and waterline cleaning create a visible trade-up.", lawnContext: "In-ground residential pools", markets: ["North America", "Europe"], channels: ["Specialist dealer", "Ecommerce"], technologyDirection: "Multi-surface cleaning platform", opportunity: "The product earns a premium when coverage and ownership convenience are clear, not merely when more modes appear on the box.", verificationRisk: "Test wall transition, waterline behaviour, pool-shape coverage and recovery after interrupted cycles.", image: "/images/sourcing/pool-robots/rm-02-wall-climbing-concept.png", imageAlt: "Illustrative wall-climbing robotic pool cleaner in an in-ground pool" },
      { id: "RM-03", name: "Cordless Premium Platform", positioning: "A premium cordless route for buyers seeking less cable friction and stronger perceived ownership convenience.", lawnContext: "Premium residential pools", markets: ["United States", "Europe"], channels: ["Specialist dealer", "Private label"], technologyDirection: "Cordless premium architecture", opportunity: "Cordless positioning can create a persuasive premium story when runtime, retrieval and durability support it.", verificationRisk: "Prove battery ageing, waterproof integrity, charging reliability and usable cleaning time across pool conditions.", image: "/images/sourcing/pool-robots/rm-03-cordless-premium-concept.png", imageAlt: "Illustrative premium cordless robotic pool cleaner" },
      { id: "RM-04", name: "Proven Corded Value", positioning: "A dependable corded platform for buyers prioritising mature operation and controlled product cost.", lawnContext: "Standard residential pools", markets: ["Europe", "Value-led markets"], channels: ["Retail", "Private label"], technologyDirection: "Established corded architecture", opportunity: "A proven platform can still win where reliability, serviceability and accessible price matter more than novelty.", verificationRisk: "Model cable tangling, motor life, filtration maintenance, spare parts and warranty exposure—not only the factory quote.", image: "/images/sourcing/pool-robots/rm-04-corded-value-concept.png", imageAlt: "Illustrative corded robotic pool cleaner in a residential pool" },
      { id: "RM-05", name: "Large-Pool Service Platform", positioning: "A specialist route for larger residential or light-commercial pools where uptime and service capability matter most.", lawnContext: "Large and high-use pools", markets: ["United States", "Middle East", "Europe"], channels: ["Professional / project sales", "Specialist dealer"], technologyDirection: "High-capacity service platform", opportunity: "Higher product and service value is possible when the offer reduces manual labour and downtime for pool operators.", verificationRisk: "Verify coverage efficiency, filter capacity, duty cycle, field repair and parts lead time before scaling.", image: "/images/sourcing/pool-robots/rm-05-large-pool-service-concept.png", imageAlt: "Illustrative high-capacity robotic pool cleaner in a large pool" },
      { id: "RM-06", name: "Ecommerce Value Platform", positioning: "A focused platform for online-led buyers who need a clear claim, manageable logistics and a credible ownership experience.", lawnContext: "Value-conscious pool owners", markets: ["North America", "Europe"], channels: ["Ecommerce", "Retail"], technologyDirection: "Online-first value platform", opportunity: "A narrow, well-supported use case can reduce the channel risk of opening the category online.", verificationRisk: "Prove packaging resilience, onboarding, support demand, returns and replacement-part availability before committing to volume.", image: "/images/sourcing/pool-robots/rm-06-ecommerce-value-concept.png", imageAlt: "Illustrative compact robotic pool cleaner for ecommerce" }
    ]
  }
};
