import { BrandDataTable } from "@/components/brands/BrandDataTable";
import type { ComponentProfile } from "@/lib/componentProfiles";
import { ComponentEvidenceMeta } from "./ComponentEvidence";
import { ComponentVisual } from "./ComponentVisual";

export function ComponentTechnicalSections({ profile }: { profile: ComponentProfile }) {
  const performanceVisual = profile.contentVisuals.find(({ placement }) => placement === "performance-boundaries");
  const applicationVisual = profile.contentVisuals.find(({ placement }) => placement === "application-context");
  return <><section className="section component-intelligence-section" id="specifications"><div className="insights-page-container"><header><p className="eyebrow">Specification dictionary</p><h2>What motor specifications do—and do not—mean</h2></header><div className="component-intelligence-table"><BrandDataTable caption={`${profile.name} specification dictionary`} columns={[{ key: "name", label: "Specification" }, { key: "meaning", label: "Purchasing meaning" }, { key: "boundary", label: "Reporting boundary" }, { key: "caution", label: "Comparison caution" }]} rows={profile.specifications.map((item) => ({ name: item.name, meaning: item.purchasingMeaning, boundary: item.reportingBoundary, caution: item.comparisonCaution }))} /></div>{performanceVisual ? <ComponentVisual visual={performanceVisual} guidance="Keep electrical input, airflow, pressure and calculated air power inside their stated measurement boundaries." /> : null}<div className="component-intelligence-details">{profile.specifications.map((item) => <details key={item.name}><summary>{item.name} evidence</summary><ComponentEvidenceMeta item={item} /></details>)}</div></div></section><section className="section component-intelligence-section component-intelligence-section--soft" id="applications"><div className="insights-page-container"><header><p className="eyebrow">Evidence + WCB interpretation</p><h2>Application matrix</h2><p>Official application language narrows the review; it does not prove exact product fit.</p></header>{applicationVisual ? <ComponentVisual visual={applicationVisual} guidance="Treat the photographed application as source context only. Verify the actual operating point, duty, envelope and approvals." /> : null}<div className="component-intelligence-assessments">{profile.applicationMatrix.map((item) => <article key={item.application}><div><h3>{item.application}</h3><ComponentEvidenceMeta item={item} /></div><div className="component-intelligence-wcb"><span>WCB assessment</span><p>{item.wcbAssessment}</p><dl><div><dt>Basis</dt><dd>{item.basis}</dd></div><div><dt>Limitations</dt><dd>{item.limitations}</dd></div><div><dt>Buyer action</dt><dd>{item.buyerAction}</dd></div></dl></div></article>)}</div></div></section></>;
}
